"use client";

import { useTranslation } from "../../../i18n/client.js";

export const couponsText = {
  ar: {
    pageTitle: "أكواد الخصم",
    pageDescription: "أنشئ وعدّل أكواد الخصم وحدودها وصلاحيتها.",
    create: "كود جديد",
    edit: "تعديل",
    delete: "إلغاء تفعيل",
    // table
    code: "الكود",
    type: "النوع",
    value: "القيمة",
    source: "المصدر",
    scope: "النطاق",
    usage: "الاستخدام",
    validity: "الصلاحية",
    active: "مُفعّل",
    plans: "الخطط",
    actions: "إجراءات",
    allPlans: "كل الخطط",
    unlimited: "غير محدود",
    percent: "نسبة %",
    fixed: "مبلغ ثابت",
    monthly: "شهري",
    yearly: "سنوي",
    both: "كلاهما",
    yes: "نعم",
    no: "لا",
    enabled: "شغّال",
    disabled: "معطّل",
    status: "الحالة",
    // sources
    MANUAL: "يدوي",
    GAME_REWARD: "مكافأة لعبة",
    QUIZ_REWARD: "مكافأة اختبار",
    ADMIN_GIFT: "هدية إدارية",
    all: "الكل",
    // form
    codeLabel: "الكود",
    typeLabel: "نوع الخصم",
    valueLabel: "القيمة",
    sourceLabel: "المصدر",
    scopeLabel: "النطاق (الدورة)",
    maxRedemptions: "أقصى عدد استخدامات",
    startsAt: "يبدأ في",
    endsAt: "ينتهي في",
    isActive: "مُفعّل",
    required: "هذا الحقل مطلوب",
    save: "حفظ",
    cancel: "إلغاء",
    createTitle: "إنشاء كود خصم",
    editTitle: "تعديل كود الخصم",
    deleteConfirm: "هل تريد إلغاء تفعيل هذا الكود؟",
  },
  en: {
    pageTitle: "Coupons",
    pageDescription: "Create and edit discount coupons, limits and validity.",
    create: "New coupon",
    edit: "Edit",
    delete: "Deactivate",
    code: "Code",
    type: "Type",
    value: "Value",
    source: "Source",
    scope: "Scope",
    usage: "Usage",
    validity: "Validity",
    active: "Active",
    plans: "Plans",
    actions: "Actions",
    allPlans: "All plans",
    unlimited: "Unlimited",
    percent: "Percent %",
    fixed: "Fixed amount",
    monthly: "Monthly",
    yearly: "Yearly",
    both: "Both",
    yes: "Yes",
    no: "No",
    enabled: "Active",
    disabled: "Disabled",
    status: "Status",
    MANUAL: "Manual",
    GAME_REWARD: "Game reward",
    QUIZ_REWARD: "Quiz reward",
    ADMIN_GIFT: "Admin gift",
    all: "All",
    codeLabel: "Code",
    typeLabel: "Discount type",
    valueLabel: "Value",
    sourceLabel: "Source",
    scopeLabel: "Scope (cycle)",
    maxRedemptions: "Max redemptions",
    startsAt: "Starts at",
    endsAt: "Ends at",
    isActive: "Active",
    required: "This field is required",
    save: "Save",
    cancel: "Cancel",
    createTitle: "Create a coupon",
    editTitle: "Edit coupon",
    deleteConfirm: "Deactivate this coupon?",
  },
};

export function useCouponsText() {
  const { lng } = useTranslation();
  return couponsText[lng === "en" ? "en" : "ar"];
}
