// Central SEO/site constants. Pure + isomorphic (no React, no next/headers) so
// it can be imported from layouts, pages, robots.js, sitemap.js and manifest.js.
//
// The canonical/OG URLs need the REAL production origin. Set NEXT_PUBLIC_SITE_URL
// in the deploy env (e.g. https://ayah.academy). We fall back to the brand domain
// so builds never produce relative/broken OG URLs.

import {
  defaultLng,
  fallbackLng,
  languages,
} from "@/i18n/settings.js";

export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || "https://ayah.academy"
).replace(/\/+$/, "");

// Brand name per locale — appended to page titles via the title template.
export const BRAND = {
  ar: "أكاديمية آية",
  en: "Aya Academy",
};

// Social-share cards — dedicated 1200×630 art-directed brand cards, ONE per
// locale (Arabic / English), generated by web/scripts/make-og.mjs (`npm run og`).
// buildMetadata serves the pair matching the page locale, so an /ar link shares
// the Arabic card and an /en link shares the English one. Within each pair the
// PNG is the canonical card; the lighter JPEG is a fallback for scrapers that
// drop large images (WhatsApp / Facebook). Listed PNG-first so quality-capable
// platforms (Twitter/X, LinkedIn) pick the crisp one.
export const DEFAULT_OG_IMAGE = "/og-en.png";
export const OG_IMAGES = {
  ar: [
    { url: "/og.png", type: "image/png" },
    { url: "/og-share.jpg", type: "image/jpeg" },
  ],
  en: [
    { url: "/og-en.png", type: "image/png" },
    { url: "/og-en-share.jpg", type: "image/jpeg" },
  ],
};

export function ogImages(lng) {
  return OG_IMAGES[lng] || OG_IMAGES[fallbackLng];
}

// OpenGraph locale tags (BCP-47-ish) keyed by our short locale codes.
export const OG_LOCALE = {
  ar: "ar_AR",
  en: "en_US",
};

export const THEME_COLOR = "#1ABC9C";
export const BACKGROUND_COLOR = "#ffffff";

export { defaultLng, fallbackLng, languages };

export function brand(lng) {
  return BRAND[lng] || BRAND[fallbackLng];
}

export function ogLocale(lng) {
  return OG_LOCALE[lng] || OG_LOCALE[fallbackLng];
}
