// Central SEO/site constants. Pure + isomorphic (no React, no next/headers) so
// it can be imported from layouts, pages, robots.js, sitemap.js and manifest.js.
//
// The canonical/OG URLs need the REAL production origin. Set NEXT_PUBLIC_SITE_URL
// in the deploy env (e.g. https://ayah.academy). We fall back to the brand domain
// so builds never produce relative/broken OG URLs.

import {
  defaultLng,
  fallbackLng,
  languages,
} from "@/i18n/settings.js";

export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL || "https://ayah.academy"
).replace(/\/+$/, "");

// One canonical entity name across every locale and every machine-readable
// surface. Localized labels remain useful in visible page titles, but Google
// should never see the same Organization/WebSite @id renamed by locale.
export const SITE_NAME = "Ayah Academy";
export const SITE_ALTERNATE_NAMES = [
  "Ayah",
  "أكاديمية آية",
  "ayah.academy",
];

// Brand name per locale — appended to page titles via the title template.
export const BRAND = {
  ar: "أكاديمية آية",
  en: SITE_NAME,
};

// The cross-language name gives search engines one stable entity with two
// legitimate labels. Keep old/misspelled brand variants out of this list so the
// canonical English name remains unambiguous.
export const BRAND_ALTERNATES = {
  ar: "Ayah Academy",
  en: "أكاديمية آية",
};

// Official profiles can be added here once the real handles are available.
// Keep these examples commented: fake/placeholder URLs must never reach `sameAs`.
const SOCIAL_PROFILE_URLS_FROM_CODE = [
  // "https://www.facebook.com/REAL_AYAH_ACADEMY_HANDLE",
  // "https://www.instagram.com/REAL_AYAH_ACADEMY_HANDLE",
  // "https://www.youtube.com/@REAL_AYAH_ACADEMY_HANDLE",
  // "https://www.tiktok.com/@REAL_AYAH_ACADEMY_HANDLE",
];

// Or configure the same official URLs at build time as a comma-separated list:
// NEXT_PUBLIC_SOCIAL_PROFILE_URLS=https://www.facebook.com/REAL_HANDLE,https://www.instagram.com/REAL_HANDLE
// `sameAs` is only emitted for valid absolute HTTP(S) URLs; no profile is ever
// guessed or invented in source code.
export const SOCIAL_PROFILE_URLS = [
  ...new Set(
    [
      ...SOCIAL_PROFILE_URLS_FROM_CODE,
      ...(process.env.NEXT_PUBLIC_SOCIAL_PROFILE_URLS || "").split(","),
    ]
      .map((value) => value.trim())
      .filter((value) => {
        if (!value) return false;
        try {
          const url = new URL(value);
          return url.protocol === "https:" || url.protocol === "http:";
        } catch {
          return false;
        }
      }),
  ),
];

// Social-share cards — dedicated 1200×630 art-directed brand cards, ONE per
// locale (Arabic / English), generated by web/scripts/make-og.mjs (`npm run og`).
// buildMetadata serves the pair matching the page locale, so an /ar link shares
// the Arabic card and an /en link shares the English one. Within each pair the
// PNG is the canonical card; the lighter JPEG is a fallback for scrapers that
// drop large images (WhatsApp / Facebook). Listed PNG-first so quality-capable
// platforms (Twitter/X, LinkedIn) pick the crisp one.
export const DEFAULT_OG_IMAGE = "/og-en.png";
export const OG_IMAGES = {
  ar: [
    { url: "/og.png", type: "image/png" },
    { url: "/og-share.jpg", type: "image/jpeg" },
  ],
  en: [
    { url: "/og-en.png", type: "image/png" },
    { url: "/og-en-share.jpg", type: "image/jpeg" },
  ],
};

export function ogImages(lng) {
  return OG_IMAGES[lng] || OG_IMAGES[fallbackLng];
}

// OpenGraph locale tags (BCP-47-ish) keyed by our short locale codes.
export const OG_LOCALE = {
  ar: "ar_AR",
  en: "en_US",
};

export const THEME_COLOR = "#1ABC9C";
export const BACKGROUND_COLOR = "#ffffff";

export { defaultLng, fallbackLng, languages };

export function brand(lng) {
  return BRAND[lng] || BRAND[fallbackLng];
}

export function brandAlternate(lng) {
  return BRAND_ALTERNATES[lng] || BRAND_ALTERNATES[fallbackLng];
}

export function ogLocale(lng) {
  return OG_LOCALE[lng] || OG_LOCALE[fallbackLng];
}
