"use client";

import { useTranslation } from "../../../i18n/client.js";

export const quizBankText = {
  ar: {
    pageTitle: "بنك الأسئلة",
    pageDescription: "أنشئ وأدِر الأسئلة التي يبني منها أولياء الأمور الاختبارات.",
    // actions
    create: "إضافة سؤال",
    edit: "تعديل",
    delete: "حذف",
    manageCategories: "إدارة التصنيفات",
    // columns
    text: "نص السؤال",
    category: "التصنيف",
    options: "الخيارات",
    status: "الحالة",
    createdAt: "أُنشئ في",
    actions: "إجراءات",
    noCategory: "بدون تصنيف",
    active: "مُفعّل",
    inactive: "غير مُفعّل",
    // filters
    searchLabel: "بحث",
    allCategories: "كل التصنيفات",
    allStatuses: "كل الحالات",
    // dialog
    createTitle: "إضافة سؤال جديد",
    editTitle: "تعديل السؤال",
    textArLabel: "نص السؤال (عربي)",
    textEnLabel: "نص السؤال (إنجليزي)",
    categoryLabel: "التصنيف",
    isActiveLabel: "مُفعّل",
    optionsTitle: "الخيارات",
    optionsHint: "أضف خيارين على الأقل، وحدِّد إجابة صحيحة واحدة على الأقل.",
    optionArLabel: "الخيار (عربي)",
    optionEnLabel: "الخيار (إنجليزي)",
    correct: "إجابة صحيحة",
    addOption: "إضافة خيار",
    removeOption: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    // validation
    required: "هذا الحقل مطلوب",
    minOptions: "أضف خيارين على الأقل.",
    minCorrect: "حدِّد إجابة صحيحة واحدة على الأقل.",
    // delete confirm
    deleteTitle: "حذف السؤال؟",
    deleteDescription: "لن يظهر هذا السؤال بعد الآن عند بناء اختبارات جديدة.",
    deleteConfirm: "حذف",
    // categories dialog
    categoriesTitle: "إدارة التصنيفات",
    categoriesHint: "تُستخدم التصنيفات لتنظيم أسئلة البنك.",
    catNameAr: "الاسم (عربي)",
    catNameEn: "الاسم (إنجليزي)",
    addCategory: "إضافة",
    saveCategory: "حفظ",
    editCategory: "تعديل",
    deleteCategory: "حذف",
    deleteCatTitle: "حذف التصنيف؟",
    deleteCatDescription: "سيُزال هذا التصنيف. لن تُحذف الأسئلة المرتبطة به.",
    noCategories: "لا توجد تصنيفات بعد.",
    close: "إغلاق",
  },
  en: {
    pageTitle: "Question bank",
    pageDescription: "Create and manage the questions parents build quizzes from.",
    create: "Add question",
    edit: "Edit",
    delete: "Delete",
    manageCategories: "Manage categories",
    text: "Question",
    category: "Category",
    options: "Options",
    status: "Status",
    createdAt: "Created",
    actions: "Actions",
    noCategory: "No category",
    active: "Active",
    inactive: "Inactive",
    searchLabel: "Search",
    allCategories: "All categories",
    allStatuses: "All statuses",
    createTitle: "Add a new question",
    editTitle: "Edit question",
    textArLabel: "Question text (Arabic)",
    textEnLabel: "Question text (English)",
    categoryLabel: "Category",
    isActiveLabel: "Active",
    optionsTitle: "Options",
    optionsHint: "Add at least 2 options and mark at least 1 as correct.",
    optionArLabel: "Option (Arabic)",
    optionEnLabel: "Option (English)",
    correct: "Correct",
    addOption: "Add option",
    removeOption: "Remove",
    save: "Save",
    cancel: "Cancel",
    required: "This field is required",
    minOptions: "Add at least 2 options.",
    minCorrect: "Mark at least 1 option as correct.",
    deleteTitle: "Delete question?",
    deleteDescription: "This question will no longer appear when building new quizzes.",
    deleteConfirm: "Delete",
    categoriesTitle: "Manage categories",
    categoriesHint: "Categories help organize the question bank.",
    catNameAr: "Name (Arabic)",
    catNameEn: "Name (English)",
    addCategory: "Add",
    saveCategory: "Save",
    editCategory: "Edit",
    deleteCategory: "Delete",
    deleteCatTitle: "Delete category?",
    deleteCatDescription: "This category will be removed. Linked questions are kept.",
    noCategories: "No categories yet.",
    close: "Close",
  },
};

export function useQuizBankText() {
  const { lng } = useTranslation();
  return quizBankText[lng === "en" ? "en" : "ar"];
}
