"use client";

import { useTranslation } from "../../../i18n/client.js";

export const certificateTemplatesText = {
  ar: {
    pageTitle: "قوالب الشهادات",
    pageDescription: "أنشئ وعدّل قوالب الشهادات (النصوص الثابتة + التصميم).",
    create: "قالب جديد",
    createTitle: "إنشاء قالب",
    editTitle: "تعديل قالب",
    // columns
    name: "الاسم",
    key: "المفتاح",
    type: "النوع",
    isDefault: "افتراضي",
    isActive: "مفعّل",
    yes: "نعم",
    no: "لا",
    active: "مفعّل",
    inactive: "متوقف",
    actions: "إجراءات",
    edit: "تعديل",
    delete: "حذف",
    deleteConfirm: "هل تريد حذف هذا القالب؟",
    empty: "لا توجد قوالب بعد",
    // form sections
    sectionTexts: "النصوص الثابتة",
    sectionSignature: "التوقيع",
    sectionStyle: "التصميم",
    sectionMore: "خيارات إضافية",
    // template type
    typeLabel: "نوع القالب",
    typeGeneral: "عام",
    typeGame: "قالب الألعاب",
    typeGameHint:
      "قالب الألعاب يُستخدم تلقائيًا مع كل شهادات الألعاب (اسم اللعبة يحلّ محل {reason}). يوجد قالب ألعاب واحد فقط — اختيار قالب جديد كقالب ألعاب يُلغي القديم.",
    // form fields
    keyLabel: "المفتاح (معرّف فريد)",
    nameArLabel: "الاسم (عربي)",
    nameEnLabel: "الاسم (إنجليزي)",
    headingArLabel: "العنوان الرئيسي (عربي)",
    headingEnLabel: "العنوان الرئيسي (إنجليزي)",
    introArLabel: "سطر المقدمة (عربي)",
    introEnLabel: "سطر المقدمة (إنجليزي)",
    bodyArLabel: "النص (عربي)",
    bodyEnLabel: "النص (إنجليزي)",
    bodyHint: "استخدم {reason} ليُستبدل بسبب المنح. إن لم تضع الرمز يُضاف السبب في سطر منفصل.",
    congratsArLabel: "عبارة التهنئة (عربي)",
    congratsEnLabel: "عبارة التهنئة (إنجليزي)",
    thanksArLabel: "عبارة الشكر (عربي)",
    thanksEnLabel: "عبارة الشكر (إنجليزي)",
    signatureNameLabel: "اسم الموقِّع",
    signatureTitleArLabel: "صفة الموقِّع (عربي)",
    signatureTitleEnLabel: "صفة الموقِّع (إنجليزي)",
    orientationLabel: "اتجاه الشهادة",
    orientationPortrait: "عمودي",
    orientationLandscape: "أفقي",
    borderStyleLabel: "نمط الإطار",
    borderOrnate: "زخرفي (إسلامي)",
    borderFoil: "مزدوج",
    borderDouble: "خطّان",
    borderSimple: "بسيط",
    borderRounded: "دائري",
    borderDashed: "متقطّع",
    borderInset: "غائر",
    borderGroove: "محفور",
    borderRibbon: "شريطي",
    borderNone: "بدون إطار",
    accentLabel: "اللون الأساسي",
    secondaryLabel: "اللون الذهبي / الثانوي",
    backgroundLabel: "لون الخلفية",
    nameColorLabel: "لون اسم الطالب",
    showPhotoLabel: "إظهار صورة الطالب",
    showBismillahLabel: "إظهار البسملة",
    // extra style options
    decorationLabel: "الزخرفة",
    decoElegant: "أنيقة",
    decoGeometric: "هندسية",
    decoClassic: "كلاسيكية",
    decoStars: "نجوم",
    decoRainbow: "قوس قزح",
    decoCrescent: "هلال",
    decoBalloons: "بالونات",
    decoBadges: "أوسمة",
    decoConfetti: "قصاصات ملوّنة",
    decoHearts: "قلوب",
    decoLanterns: "فوانيس",
    decoFlorals: "أزهار",
    decoSparkles: "بريق",
    decoNone: "بدون زخرفة",
    fontStyleLabel: "نمط الخط",
    fontElegant: "أميري (أنيق)",
    fontClassic: "شهرزاد (كلاسيكي)",
    fontModern: "القاهرة (حديث)",
    fontKufi: "كوفي",
    fontRuqaa: "رقعة",
    fontNaskh: "نسخ",
    logoSizeLabel: "حجم الشعار",
    logoSizeSm: "صغير",
    logoSizeMd: "متوسط",
    logoSizeLg: "كبير",
    showSealLabel: "إظهار الختم",
    sealTextLabel: "نص الختم",
    showWatermarkLabel: "إظهار العلامة المائية",
    watermarkOpacityLabel: "شفافية العلامة المائية",
    showTaglineLabel: "إظهار شعار الأكاديمية",
    showDateLabel: "إظهار التاريخ",
    nameScaleLabel: "حجم اسم الطالب",
    headingScaleLabel: "حجم العنوان الرئيسي",
    contentSpacingLabel: "تباعد المحتوى",
    isActiveLabel: "مفعّل",
    isDefaultLabel: "القالب الافتراضي",
    previewLabel: "معاينة مباشرة",
    previewStudent: "اسم الطالب",
    previewReason: "حفظ سورة الفاتحة",
    save: "حفظ",
    cancel: "إلغاء",
    required: "هذا الحقل مطلوب",
    // default texts used to pre-fill a brand-new template (match the card).
    defaultHeadingAr: "شهادة تقدير",
    defaultHeadingEn: "Certificate of Achievement",
    defaultIntroAr: "تُمنح هذه الشهادة إلى",
    defaultIntroEn: "This certificate is proudly awarded to",
    defaultBodyAr: "تقديرًا لجهوده المتميّزة في {reason}",
    defaultBodyEn: "in recognition of outstanding effort in {reason}",
    defaultCongratsAr: "بارك الله فيك وأحسن إليك",
    defaultCongratsEn: "Congratulations on your achievement!",
    defaultThanksAr: "نسأل الله لك دوام التوفيق والسداد",
    defaultThanksEn: "We wish you continued success.",
    defaultSignatureName: "إدارة الأكاديمية",
    defaultSignatureTitleAr: "التوقيع",
    defaultSignatureTitleEn: "Signature",
  },
  en: {
    pageTitle: "Certificate templates",
    pageDescription: "Create and edit certificate templates (fixed texts + design).",
    create: "New template",
    createTitle: "Create template",
    editTitle: "Edit template",
    name: "Name",
    key: "Key",
    type: "Type",
    isDefault: "Default",
    isActive: "Active",
    yes: "Yes",
    no: "No",
    active: "Active",
    inactive: "Inactive",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    deleteConfirm: "Delete this template?",
    empty: "No templates yet",
    sectionTexts: "Fixed texts",
    sectionSignature: "Signature",
    sectionStyle: "Design",
    sectionMore: "More options",
    typeLabel: "Template type",
    typeGeneral: "General",
    typeGame: "Games template",
    typeGameHint:
      "The games template is applied automatically to every game certificate (the game name replaces {reason}). Only one games template exists — choosing a new one replaces the old.",
    keyLabel: "Key (unique id)",
    nameArLabel: "Name (Arabic)",
    nameEnLabel: "Name (English)",
    headingArLabel: "Heading (Arabic)",
    headingEnLabel: "Heading (English)",
    introArLabel: "Intro line (Arabic)",
    introEnLabel: "Intro line (English)",
    bodyArLabel: "Body (Arabic)",
    bodyEnLabel: "Body (English)",
    bodyHint: "Use {reason} to substitute the awarding reason. If omitted, the reason is appended on its own line.",
    congratsArLabel: "Congrats line (Arabic)",
    congratsEnLabel: "Congrats line (English)",
    thanksArLabel: "Thanks line (Arabic)",
    thanksEnLabel: "Thanks line (English)",
    signatureNameLabel: "Signed by",
    signatureTitleArLabel: "Signature title (Arabic)",
    signatureTitleEnLabel: "Signature title (English)",
    orientationLabel: "Orientation",
    orientationPortrait: "Portrait",
    orientationLandscape: "Landscape",
    borderStyleLabel: "Border style",
    borderOrnate: "Ornate (Islamic)",
    borderFoil: "Foil",
    borderDouble: "Double",
    borderSimple: "Simple",
    borderRounded: "Rounded",
    borderDashed: "Dashed",
    borderInset: "Inset",
    borderGroove: "Groove",
    borderRibbon: "Ribbon",
    borderNone: "No border",
    accentLabel: "Accent color",
    secondaryLabel: "Gold / secondary color",
    backgroundLabel: "Background color",
    nameColorLabel: "Student-name color",
    showPhotoLabel: "Show student photo",
    showBismillahLabel: "Show Bismillah",
    decorationLabel: "Decoration",
    decoElegant: "Elegant",
    decoGeometric: "Geometric",
    decoClassic: "Classic",
    decoStars: "Stars",
    decoRainbow: "Rainbow",
    decoCrescent: "Crescent",
    decoBalloons: "Balloons",
    decoBadges: "Badges",
    decoConfetti: "Confetti",
    decoHearts: "Hearts",
    decoLanterns: "Lanterns",
    decoFlorals: "Florals",
    decoSparkles: "Sparkles",
    decoNone: "None",
    fontStyleLabel: "Font style",
    fontElegant: "Amiri (elegant)",
    fontClassic: "Scheherazade (classic)",
    fontModern: "Cairo (modern)",
    fontKufi: "Kufi",
    fontRuqaa: "Ruqaa",
    fontNaskh: "Naskh",
    logoSizeLabel: "Logo size",
    logoSizeSm: "Small",
    logoSizeMd: "Medium",
    logoSizeLg: "Large",
    showSealLabel: "Show seal",
    sealTextLabel: "Seal text",
    showWatermarkLabel: "Show watermark",
    watermarkOpacityLabel: "Watermark opacity",
    showTaglineLabel: "Show academy tagline",
    showDateLabel: "Show date",
    nameScaleLabel: "Student-name size",
    headingScaleLabel: "Heading size",
    contentSpacingLabel: "Content spacing",
    isActiveLabel: "Active",
    isDefaultLabel: "Default template",
    previewLabel: "Live preview",
    previewStudent: "Student name",
    previewReason: "memorizing Surah Al-Fatihah",
    save: "Save",
    cancel: "Cancel",
    required: "This field is required",
    // default texts used to pre-fill a brand-new template (match the card).
    defaultHeadingAr: "شهادة تقدير",
    defaultHeadingEn: "Certificate of Achievement",
    defaultIntroAr: "تُمنح هذه الشهادة إلى",
    defaultIntroEn: "This certificate is proudly awarded to",
    defaultBodyAr: "تقديرًا لجهوده المتميّزة في {reason}",
    defaultBodyEn: "in recognition of outstanding effort in {reason}",
    defaultCongratsAr: "بارك الله فيك وأحسن إليك",
    defaultCongratsEn: "Congratulations on your achievement!",
    defaultThanksAr: "نسأل الله لك دوام التوفيق والسداد",
    defaultThanksEn: "We wish you continued success.",
    defaultSignatureName: "إدارة الأكاديمية",
    defaultSignatureTitleAr: "التوقيع",
    defaultSignatureTitleEn: "Signature",
  },
};

export function useCertificateTemplatesText() {
  const { lng } = useTranslation();
  return certificateTemplatesText[lng === "en" ? "en" : "ar"];
}
