"use client";

import { useTranslation } from "../../../i18n/client.js";

export const certificateTemplatesText = {
  ar: {
    pageTitle: "قوالب الشهادات",
    pageDescription: "أنشئ وعدّل قوالب الشهادات (النصوص الثابتة + التصميم).",
    create: "قالب جديد",
    createTitle: "إنشاء قالب",
    editTitle: "تعديل قالب",
    // columns
    name: "الاسم",
    key: "المفتاح",
    isDefault: "افتراضي",
    isActive: "مفعّل",
    yes: "نعم",
    no: "لا",
    active: "مفعّل",
    inactive: "متوقف",
    actions: "إجراءات",
    edit: "تعديل",
    delete: "حذف",
    deleteConfirm: "هل تريد حذف هذا القالب؟",
    empty: "لا توجد قوالب بعد",
    // form sections
    sectionTexts: "النصوص الثابتة",
    sectionSignature: "التوقيع",
    sectionStyle: "التصميم",
    // form fields
    keyLabel: "المفتاح (معرّف فريد)",
    nameArLabel: "الاسم (عربي)",
    nameEnLabel: "الاسم (إنجليزي)",
    headingArLabel: "العنوان الرئيسي (عربي)",
    headingEnLabel: "العنوان الرئيسي (إنجليزي)",
    introArLabel: "سطر المقدمة (عربي)",
    introEnLabel: "سطر المقدمة (إنجليزي)",
    bodyArLabel: "النص (عربي)",
    bodyEnLabel: "النص (إنجليزي)",
    bodyHint: "استخدم {reason} ليُستبدل بسبب المنح. إن لم تضع الرمز يُضاف السبب في سطر منفصل.",
    congratsArLabel: "عبارة التهنئة (عربي)",
    congratsEnLabel: "عبارة التهنئة (إنجليزي)",
    thanksArLabel: "عبارة الشكر (عربي)",
    thanksEnLabel: "عبارة الشكر (إنجليزي)",
    signatureNameLabel: "اسم الموقِّع",
    signatureTitleArLabel: "صفة الموقِّع (عربي)",
    signatureTitleEnLabel: "صفة الموقِّع (إنجليزي)",
    orientationLabel: "اتجاه الشهادة",
    orientationPortrait: "عمودي",
    orientationLandscape: "أفقي",
    borderStyleLabel: "نمط الإطار",
    borderOrnate: "زخرفي (إسلامي)",
    borderFoil: "مزدوج",
    borderDouble: "خطّان",
    borderSimple: "بسيط",
    accentLabel: "اللون الأساسي",
    secondaryLabel: "اللون الذهبي / الثانوي",
    backgroundLabel: "لون الخلفية",
    showPhotoLabel: "إظهار صورة الطالب",
    showBismillahLabel: "إظهار البسملة",
    isActiveLabel: "مفعّل",
    isDefaultLabel: "القالب الافتراضي",
    previewLabel: "معاينة مباشرة",
    previewStudent: "اسم الطالب",
    previewReason: "حفظ سورة الفاتحة",
    save: "حفظ",
    cancel: "إلغاء",
    required: "هذا الحقل مطلوب",
  },
  en: {
    pageTitle: "Certificate templates",
    pageDescription: "Create and edit certificate templates (fixed texts + design).",
    create: "New template",
    createTitle: "Create template",
    editTitle: "Edit template",
    name: "Name",
    key: "Key",
    isDefault: "Default",
    isActive: "Active",
    yes: "Yes",
    no: "No",
    active: "Active",
    inactive: "Inactive",
    actions: "Actions",
    edit: "Edit",
    delete: "Delete",
    deleteConfirm: "Delete this template?",
    empty: "No templates yet",
    sectionTexts: "Fixed texts",
    sectionSignature: "Signature",
    sectionStyle: "Design",
    keyLabel: "Key (unique id)",
    nameArLabel: "Name (Arabic)",
    nameEnLabel: "Name (English)",
    headingArLabel: "Heading (Arabic)",
    headingEnLabel: "Heading (English)",
    introArLabel: "Intro line (Arabic)",
    introEnLabel: "Intro line (English)",
    bodyArLabel: "Body (Arabic)",
    bodyEnLabel: "Body (English)",
    bodyHint: "Use {reason} to substitute the awarding reason. If omitted, the reason is appended on its own line.",
    congratsArLabel: "Congrats line (Arabic)",
    congratsEnLabel: "Congrats line (English)",
    thanksArLabel: "Thanks line (Arabic)",
    thanksEnLabel: "Thanks line (English)",
    signatureNameLabel: "Signed by",
    signatureTitleArLabel: "Signature title (Arabic)",
    signatureTitleEnLabel: "Signature title (English)",
    orientationLabel: "Orientation",
    orientationPortrait: "Portrait",
    orientationLandscape: "Landscape",
    borderStyleLabel: "Border style",
    borderOrnate: "Ornate (Islamic)",
    borderFoil: "Foil",
    borderDouble: "Double",
    borderSimple: "Simple",
    accentLabel: "Accent color",
    secondaryLabel: "Gold / secondary color",
    backgroundLabel: "Background color",
    showPhotoLabel: "Show student photo",
    showBismillahLabel: "Show Bismillah",
    isActiveLabel: "Active",
    isDefaultLabel: "Default template",
    previewLabel: "Live preview",
    previewStudent: "Student name",
    previewReason: "memorizing Surah Al-Fatihah",
    save: "Save",
    cancel: "Cancel",
    required: "This field is required",
  },
};

export function useCertificateTemplatesText() {
  const { lng } = useTranslation();
  return certificateTemplatesText[lng === "en" ? "en" : "ar"];
}
