"use client";

// Feature-local bilingual strings for the auth screens. We keep these here (not
// in the central i18n/locales registry) so the auth feature owns its copy.
// Select the active language with `useAuthText()` which reads useTranslation().lng.

import { useTranslation } from "../../../i18n/client.js";

export const authText = {
  ar: {
    // login
    loginTitle: "تسجيل الدخول",
    loginSubtitle: "أهلاً بعودتك إلى أكاديمية آية",
    loginButton: "دخول",
    // register
    registerTitle: "إنشاء حساب ولي أمر",
    registerSubtitle: "ابدأ رحلة طفلك مع القرآن الكريم",
    registerButton: "إنشاء الحساب",
    // fields
    name: "الاسم الكامل",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    phone: "رقم الهاتف",
    // links
    noAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    goRegister: "أنشئ حساباً",
    goLogin: "سجّل الدخول",
    backHome: "العودة للرئيسية",
    // validation
    required: "هذا الحقل مطلوب",
    invalidEmail: "بريد إلكتروني غير صالح",
    passwordShort: "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
    invalidPhone: "رقم هاتف غير صالح",
    registerSuccess: "تم إنشاء الحساب بنجاح، يمكنك تسجيل الدخول الآن",
    // wizard
    wizardTitle: "التسجيل في أكاديمية آية",
    wizardSubtitle: "أضف أبناءك واختر الخطة المناسبة",
    stepChildren: "الأبناء والخطط",
    stepReview: "المراجعة وبيانات ولي الأمر",
    childTitle: "بيانات الطالب",
    childNumber: "الطالب",
    childName: "الاسم",
    nickname: "اللقب (اختياري)",
    birthDate: "تاريخ الميلاد (اختياري)",
    monthly: "شهري",
    yearly: "سنوي",
    perMonth: "/ شهر",
    perYear: "/ سنة",
    hours: "ساعة",
    was: "كان",
    choosePlan: "اختر الخطة",
    featured: "الأكثر اختياراً",
    noPlans: "لا توجد خطط متاحة حالياً",
    couponLabel: "كود الخصم",
    couponPlaceholder: "أدخل كود الخصم إن وجد",
    verifyCoupon: "تحقق",
    verifying: "جارٍ التحقق…",
    removeCoupon: "إزالة الكوبون",
    couponApplied: "تم تطبيق الخصم 🎉",
    planCouponTitle: "🎁 كوبون الباقة المميزة",
    planCouponNote: "مطبّق تلقائيًا — لا يمكن إزالته",
    couponInvalid: "كود الخصم غير صالح",
    couponExpired: "انتهت صلاحية كود الخصم",
    couponNotApplicable: "الكوبون لا ينطبق على هذه الخطة أو الدورة",
    couponNotFound: "كود الخصم غير موجود",
    selectPlanFirst: "اختر خطة أولاً قبل التحقق من الكوبون",
    giftBanner: "🎁 أول حصة مجانية لكل ابن",
    paymentNotice:
      "الاشتراك لا يتطلب دفعاً الآن — الدفع يكون بعد أول حصة. الاختيار للتسجيل فقط.",
    addChild: "إضافة ابن آخر",
    removeChild: "حذف هذا الابن",
    next: "التالي",
    back: "السابق",
    summaryTitle: "ملخص الطلب",
    colChild: "الابن",
    colPlan: "الخطة",
    colCycle: "الدورة",
    colBase: "السعر",
    colDiscount: "الخصم",
    colNet: "الصافي",
    colGift: "هدية",
    firstSessionFree: "أول حصة مجانية",
    parentTitle: "بيانات ولي الأمر",
    submit: "تسجيل",
    submitting: "جارٍ التسجيل…",
    fixErrors: "بعض البيانات غير مكتملة، يرجى المراجعة",
    planRequired: "اختر خطة لهذا الابن",
  },
  en: {
    loginTitle: "Sign in",
    loginSubtitle: "Welcome back to Aya Academy",
    loginButton: "Log in",
    registerTitle: "Create a parent account",
    registerSubtitle: "Start your child's Quran journey",
    registerButton: "Create account",
    name: "Full name",
    email: "Email",
    password: "Password",
    phone: "Phone number",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    goRegister: "Create one",
    goLogin: "Sign in",
    backHome: "Back to home",
    required: "This field is required",
    invalidEmail: "Invalid email address",
    passwordShort: "Password must be at least 6 characters",
    invalidPhone: "Invalid phone number",
    registerSuccess: "Account created. You can sign in now.",
    // wizard
    wizardTitle: "Join Aya Academy",
    wizardSubtitle: "Add your children and choose a plan",
    stepChildren: "Children & plans",
    stepReview: "Review & parent details",
    childTitle: "Student details",
    childNumber: "Student",
    childName: "Name",
    nickname: "Nickname (optional)",
    birthDate: "Date of birth (optional)",
    monthly: "Monthly",
    yearly: "Yearly",
    perMonth: "/ mo",
    perYear: "/ yr",
    hours: "hours",
    was: "was",
    choosePlan: "Choose a plan",
    featured: "Most popular",
    noPlans: "No plans available right now",
    couponLabel: "Coupon code",
    couponPlaceholder: "Enter a coupon code if you have one",
    verifyCoupon: "Verify",
    verifying: "Verifying…",
    removeCoupon: "Remove coupon",
    couponApplied: "Discount applied 🎉",
    planCouponTitle: "🎁 Plan coupon",
    planCouponNote: "Applied automatically — can't be removed",
    couponInvalid: "Invalid coupon code",
    couponExpired: "Coupon code expired",
    couponNotApplicable: "Coupon does not apply to this plan or cycle",
    couponNotFound: "Coupon code not found",
    selectPlanFirst: "Select a plan first before verifying a coupon",
    giftBanner: "🎁 First session free for every child",
    paymentNotice:
      "No payment is required now — you pay after the first session. The selection is for registration only.",
    addChild: "Add another child",
    removeChild: "Remove this child",
    next: "Next",
    back: "Back",
    summaryTitle: "Order summary",
    colChild: "Child",
    colPlan: "Plan",
    colCycle: "Cycle",
    colBase: "Price",
    colDiscount: "Discount",
    colNet: "Net",
    colGift: "Gift",
    firstSessionFree: "First session free",
    parentTitle: "Parent details",
    submit: "Register",
    submitting: "Registering…",
    fixErrors: "Some details are incomplete, please review",
    planRequired: "Choose a plan for this child",
  },
};

export function useAuthText() {
  const { lng } = useTranslation();
  return authText[lng === "en" ? "en" : "ar"];
}
