"use client";

// Feature-local bilingual strings for the auth screens. We keep these here (not
// in the central i18n/locales registry) so the auth feature owns its copy.
// Select the active language with `useAuthText()` which reads useTranslation().lng.

import { useTranslation } from "../../../i18n/client.js";

export const authText = {
  ar: {
    // login
    loginTitle: "تسجيل الدخول",
    loginSubtitle: "أهلاً بعودتك إلى أكاديمية آية",
    loginButton: "دخول",
    // register
    registerTitle: "إنشاء حساب ولي أمر",
    registerSubtitle: "ابدأ رحلة طفلك مع القرآن الكريم",
    registerButton: "إنشاء الحساب",
    // fields
    name: "الاسم الكامل",
    email: "البريد الإلكتروني",
    username: "اسم المستخدم",
    emailOrUsername: "البريد الإلكتروني أو اسم المستخدم",
    emailOptional: "البريد الإلكتروني (اختياري)",
    usernameOptional: "اسم المستخدم (اختياري)",
    usernameFormatHint: "من 3 إلى 30 حرفًا، بدون مسافات",
    identityChoiceTitle: "اختر طريقة تسجيل الدخول",
    identityChoiceHint:
      "أدخل البريد الإلكتروني أو اسم المستخدم — واحد منهما فقط يكفي، ويمكنك إدخال الاثنين.",
    usernameHint: "3–30 حرفًا؛ البريد أو اسم المستخدم، واحد منهما مطلوب",
    password: "كلمة المرور",
    phone: "رقم الهاتف",
    // links
    noAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    goRegister: "أنشئ حساباً",
    goLogin: "سجّل الدخول",
    backHome: "العودة للرئيسية",
    // validation
    required: "هذا الحقل مطلوب",
    identityRequired: "أدخل البريد الإلكتروني أو اسم المستخدم",
    invalidEmail: "بريد إلكتروني غير صالح",
    invalidUsername:
      "اسم المستخدم من 3 إلى 30 حرفًا، ويقبل الحروف والأرقام والنقطة والشرطة السفلية والشرطة العادية فقط",
    passwordShort: "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
    invalidPhone: "رقم هاتف غير صالح",
    registerSuccess: "تم إنشاء الحساب بنجاح، يمكنك تسجيل الدخول الآن",
    passwordsDontMatch: "كلمتا المرور غير متطابقتين",
    // forgot / reset password
    forgotLink: "نسيت كلمة المرور؟",
    forgotTitle: "نسيت كلمة المرور؟",
    forgotSubtitle: "أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.",
    forgotButton: "إرسال رابط إعادة التعيين",
    emailSentTitle: "تفقّد بريدك الإلكتروني ✉️",
    emailSentBody:
      "إذا كان لديك حساب لدينا، فقد أرسلنا رابط إعادة تعيين كلمة المرور إلى بريدك. تحقّق من صندوق الوارد ومجلد الرسائل غير المرغوب فيها.",
    emailSentHint: "قد يستغرق وصول الرسالة دقيقة. الرابط صالح لمدة ساعة واحدة.",
    resetTitle: "إعادة تعيين كلمة المرور",
    resetSubtitle: "اختر كلمة مرور جديدة لحسابك.",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    resetButton: "حفظ كلمة المرور",
    invalidLinkTitle: "رابط غير صالح",
    invalidLinkBody:
      "انتهت صلاحية رابط إعادة التعيين أو أنه غير صحيح. يمكنك طلب رابط جديد.",
    requestNewLink: "طلب رابط جديد",
    backToLogin: "العودة لتسجيل الدخول",
    // wizard
    appName: "أكاديمية آية",
    registrationEyebrow: "إنشاء حساب جديد",
    wizardTitle: "إنشاء حساب وليّ أمر",
    wizardSubtitle:
      "ابدأ ببيانات حسابك، ثم أضف أبناءك واختر الخطة المناسبة لكل طالب.",
    stepCounter: "الخطوة {current} من {total}",
    stepParent: "بيانات وليّ الأمر",
    stepChildren: "الأبناء والخطط",
    stepReview: "المراجعة والتسجيل",
    parentStepTitle: "أنشئ حساب وليّ الأمر",
    parentStepSubtitle:
      "أدخل بياناتك الأساسية وحدد البريد أو اسم المستخدم الذي ستسجل به الدخول.",
    childrenStepTitle: "أضف الأبناء واختر الخطط",
    childrenStepSubtitle:
      "أدخل بيانات كل طالب واختر الخطة المناسبة له. يمكنك إضافة أكثر من طالب.",
    reviewStepTitle: "راجع البيانات وأكمل التسجيل",
    reviewStepSubtitle:
      "تأكد من بيانات وليّ الأمر والأبناء والخطط قبل إنشاء الحساب.",
    childTitle: "بيانات الطالب",
    childNumber: "الطالب",
    childName: "الاسم",
    nickname: "اللقب (اختياري)",
    birthDate: "تاريخ الميلاد (اختياري)",
    monthly: "شهري",
    yearly: "سنوي",
    perMonth: "/ شهر",
    hours: "ساعة",
    was: "كان",
    choosePlan: "اختر الخطة",
    featured: "الأكثر اختياراً",
    noPlans: "لا توجد خطط متاحة حالياً",
    couponLabel: "كود الخصم",
    couponPlaceholder: "أدخل كود الخصم إن وجد",
    verifyCoupon: "تحقق",
    verifying: "جارٍ التحقق…",
    removeCoupon: "إزالة الكوبون",
    couponApplied: "تم تطبيق الخصم 🎉",
    planCouponTitle: "🎁 كوبون الباقة المميزة",
    planCouponNote: "مطبّق تلقائيًا — لا يمكن إزالته",
    couponInvalid: "كود الخصم غير صالح",
    couponExpired: "انتهت صلاحية كود الخصم",
    couponNotApplicable: "الكوبون لا ينطبق على هذه الخطة أو دورة الفوترة",
    couponNotFound: "كود الخصم غير موجود",
    selectPlanFirst: "اختر خطة أولاً قبل التحقق من الكوبون",
    giftBanner: "🎁 أول حصة مجانية لكل ابن",
    paymentNotice:
      "الاشتراك لا يتطلب دفعاً الآن — الدفع يكون بعد أول حصة. الاختيار للتسجيل فقط.",
    addChild: "إضافة ابن آخر",
    removeChild: "حذف هذا الابن",
    next: "التالي",
    back: "السابق",
    edit: "تعديل",
    summaryTitle: "ملخص الطلب",
    colChild: "الابن",
    colPlan: "الخطة",
    colCycle: "دورة الفوترة",
    colBase: "السعر",
    colDiscount: "الخصم",
    colNet: "الصافي",
    colGift: "هدية",
    firstSessionFree: "أول حصة مجانية",
    parentTitle: "بيانات ولي الأمر",
    submit: "تسجيل",
    submitting: "جارٍ التسجيل…",
    fixErrors: "بعض البيانات غير مكتملة، يرجى المراجعة",
    planRequired: "اختر خطة لهذا الابن",
  },
  en: {
    loginTitle: "Sign in",
    loginSubtitle: "Welcome back to Ayah Academy",
    loginButton: "Log in",
    registerTitle: "Create a parent account",
    registerSubtitle: "Start your child's Quran journey",
    registerButton: "Create account",
    name: "Full name",
    email: "Email",
    username: "Username",
    emailOrUsername: "Email or username",
    emailOptional: "Email (optional)",
    usernameOptional: "Username (optional)",
    usernameFormatHint: "3–30 characters, without spaces",
    identityChoiceTitle: "Choose how you will sign in",
    identityChoiceHint:
      "Enter an email or a username — either one is enough, and you may provide both.",
    usernameHint: "3–30 characters; email or username, at least one is required",
    password: "Password",
    phone: "Phone number",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    goRegister: "Create one",
    goLogin: "Sign in",
    backHome: "Back to home",
    required: "This field is required",
    identityRequired: "Enter an email address or username",
    invalidEmail: "Invalid email address",
    invalidUsername:
      "Username must be 3–30 characters using letters, numbers, dots, underscores or hyphens",
    passwordShort: "Password must be at least 6 characters",
    invalidPhone: "Invalid phone number",
    registerSuccess: "Account created. You can sign in now.",
    passwordsDontMatch: "Passwords do not match",
    // forgot / reset password
    forgotLink: "Forgot your password?",
    forgotTitle: "Forgot your password?",
    forgotSubtitle: "Enter your email and we'll send you a link to reset your password.",
    forgotButton: "Send reset link",
    emailSentTitle: "Check your email ✉️",
    emailSentBody:
      "If you have an account with us, we've sent a password reset link to your email. Check your inbox and spam folder.",
    emailSentHint: "It may take a minute to arrive. The link is valid for one hour.",
    resetTitle: "Reset your password",
    resetSubtitle: "Choose a new password for your account.",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    resetButton: "Save password",
    invalidLinkTitle: "Invalid link",
    invalidLinkBody:
      "This reset link is invalid or has expired. You can request a new one.",
    requestNewLink: "Request a new link",
    backToLogin: "Back to sign in",
    // wizard
    appName: "Ayah Academy",
    registrationEyebrow: "Create a new account",
    wizardTitle: "Create a parent account",
    wizardSubtitle:
      "Start with your account details, then add your children and choose a plan for each student.",
    stepCounter: "Step {current} of {total}",
    stepParent: "Parent details",
    stepChildren: "Children & plans",
    stepReview: "Review & register",
    parentStepTitle: "Create the parent account",
    parentStepSubtitle:
      "Enter your basic details and choose the email or username you will use to sign in.",
    childrenStepTitle: "Add children and choose plans",
    childrenStepSubtitle:
      "Enter each student's details and choose a suitable plan. You can add more than one student.",
    reviewStepTitle: "Review and complete registration",
    reviewStepSubtitle:
      "Check the parent, student, and plan details before creating the account.",
    childTitle: "Student details",
    childNumber: "Student",
    childName: "Name",
    nickname: "Nickname (optional)",
    birthDate: "Date of birth (optional)",
    monthly: "Monthly",
    yearly: "Yearly",
    perMonth: "/ mo",
    hours: "hours",
    was: "was",
    choosePlan: "Choose a plan",
    featured: "Most popular",
    noPlans: "No plans available right now",
    couponLabel: "Coupon code",
    couponPlaceholder: "Enter a coupon code if you have one",
    verifyCoupon: "Verify",
    verifying: "Verifying…",
    removeCoupon: "Remove coupon",
    couponApplied: "Discount applied 🎉",
    planCouponTitle: "🎁 Plan coupon",
    planCouponNote: "Applied automatically — can't be removed",
    couponInvalid: "Invalid coupon code",
    couponExpired: "Coupon code expired",
    couponNotApplicable: "Coupon does not apply to this plan or cycle",
    couponNotFound: "Coupon code not found",
    selectPlanFirst: "Select a plan first before verifying a coupon",
    giftBanner: "🎁 First session free for every child",
    paymentNotice:
      "No payment is required now — you pay after the first session. The selection is for registration only.",
    addChild: "Add another child",
    removeChild: "Remove this child",
    next: "Next",
    back: "Back",
    edit: "Edit",
    summaryTitle: "Order summary",
    colChild: "Child",
    colPlan: "Plan",
    colCycle: "Cycle",
    colBase: "Price",
    colDiscount: "Discount",
    colNet: "Net",
    colGift: "Gift",
    firstSessionFree: "First session free",
    parentTitle: "Parent details",
    submit: "Register",
    submitting: "Registering…",
    fixErrors: "Some details are incomplete, please review",
    planRequired: "Choose a plan for this child",
  },
};

export function useAuthText() {
  const { lng } = useTranslation();
  return authText[lng === "en" ? "en" : "ar"];
}
