import {
  Cairo,
  Geist_Mono,
  Amiri,
  Scheherazade_New,
  Reem_Kufi,
  Aref_Ruqaa,
  Noto_Naskh_Arabic,
} from 'next/font/google';
import { notFound } from 'next/navigation';
import { cookies } from 'next/headers';
import '../globals.css';
import 'react-toastify/dist/ReactToastify.css';
import ThemeTogglerProvider from '@/providers/ThemeToggler';
import AppProviders from '@/providers/AppProviders.jsx';
import WhatsAppButton from '@/shared/components/feedback/WhatsAppButton.jsx';
import JsonLd from '@/shared/components/seo/JsonLd.jsx';
import { languages, getDirection } from '@/i18n/settings.js';
import {
  buildMetadata,
  brand,
  THEME_COLOR,
  organizationSchema,
  websiteSchema,
} from '@/shared/lib/seo';

// Cairo — Arabic-first UI font with full Latin coverage and the complete weight
// range (matches the theme's 400–900). Self-hosted via next/font (no layout
// shift, no external request). Exposed as `--font-sans` for the MUI theme + CSS.
const cairo = Cairo({
  variable: '--font-sans',
  subsets: ['arabic', 'latin'],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
});

// Certificate display fonts (the admin-pickable heading/name styles). SELF-HOSTED
// via next/font so they load same-origin from /_next/static. This is what makes
// them embeddable by html-to-image at PDF/PNG/print time: the previous Google
// Fonts @import served them cross-origin (fonts.gstatic.com), which the exporter
// cannot inline — so exported certificates silently fell back to a default font.
// Each is exposed as a CSS variable consumed by FONT_STACKS (certificates config).
// Reem Kufi + Noto Naskh Arabic are variable fonts (no explicit weight); the rest
// are static and must declare their weights.
const amiri = Amiri({
  variable: '--font-amiri',
  weight: ['400', '700'],
  subsets: ['arabic', 'latin'],
  display: 'swap',
});
const scheherazade = Scheherazade_New({
  variable: '--font-scheherazade',
  weight: ['400', '700'],
  subsets: ['arabic', 'latin'],
  display: 'swap',
});
const reemKufi = Reem_Kufi({
  variable: '--font-reem-kufi',
  subsets: ['arabic', 'latin'],
  display: 'swap',
});
const arefRuqaa = Aref_Ruqaa({
  variable: '--font-aref-ruqaa',
  weight: ['400', '700'],
  subsets: ['arabic', 'latin'],
  display: 'swap',
});
const notoNaskh = Noto_Naskh_Arabic({
  variable: '--font-noto-naskh',
  subsets: ['arabic', 'latin'],
  display: 'swap',
});

export function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

// themeColor belongs in viewport (Next.js metadata API), not in metadata.
export const viewport = {
  themeColor: THEME_COLOR,
};

// Root metadata for every locale page. Sets the title TEMPLATE ("<page> | Brand")
// + site defaults; individual pages override title/description/canonical via
// their own generateMetadata (see @/shared/lib/seo). Icons + manifest are wired
// once here so the whole site inherits them.
export async function generateMetadata({ params }) {
  const { lng } = await params;
  const base = buildMetadata({ lng, page: 'site', path: '/' });
  return {
    ...base,
    title: {
      default: base.title?.absolute ?? base.title,
      template: `%s | ${brand(lng)}`,
    },
    applicationName: brand(lng),
    manifest: '/manifest.webmanifest',
    // Favicon / icon links are auto-generated by Next from the file-convention
    // assets in app/: favicon.ico, icon.png and apple-icon.png (all derived
    // from the brand logo's owl mascot).
  };
}

// Root layout for every page. The active locale comes from the [lng] URL
// segment (Arabic default, RTL). Light/dark mode is read from the cookie for a
// flash-free first paint; the client ThemeToggler takes over after hydration.
export default async function LocaleLayout({ children, params }) {
  const { lng } = await params;
  if (!languages.includes(lng)) notFound();

  const cookieStore = await cookies();
  const themeCookie = cookieStore.get('theme');
  const pageTheme = themeCookie?.value === 'dark' ? 'dark' : 'light';
  const dir = getDirection(lng);

  return (
    <html lang={lng} dir={dir} suppressHydrationWarning>
      <body
        className={`${cairo.variable} ${geistMono.variable} ${amiri.variable} ${scheherazade.variable} ${reemKufi.variable} ${arefRuqaa.variable} ${notoNaskh.variable}`}
      >
        {/* Site-wide structured data: who we are + the site/languages. */}
        <JsonLd data={[organizationSchema(lng), websiteSchema(lng)]} />
        <ThemeTogglerProvider defaultTheme={pageTheme}>
          {/* AppProviders: i18n -> theme(RTL cache) -> dates -> auth -> toast */}
          <AppProviders lng={lng} mode={pageTheme}>
            {children}
            <WhatsAppButton />
          </AppProviders>
        </ThemeTogglerProvider>
      </body>
    </html>
  );
}
