import { Cairo } from 'next/font/google';
import { notFound } from 'next/navigation';
import '../globals.css';
import AppProviders from '@/providers/AppProviders.jsx';
import WhatsAppButton from '@/shared/components/feedback/WhatsAppButton.jsx';
import JsonLd from '@/shared/components/seo/JsonLd.jsx';
import { languages, getDirection } from '@/i18n/settings.js';
import {
  buildMetadata,
  brand,
  THEME_COLOR,
  organizationSchema,
  websiteSchema,
} from '@/shared/lib/seo';

// Cairo — Arabic-first UI font with full Latin coverage and the complete weight
// range (matches the theme's 400–900). Self-hosted via next/font (no layout
// shift, no external request). Exposed as `--font-sans` for the MUI theme + CSS.
const cairo = Cairo({
  variable: '--font-sans',
  subsets: ['arabic', 'latin'],
  display: 'swap',
});

export function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

// themeColor belongs in viewport (Next.js metadata API), not in metadata.
export const viewport = {
  themeColor: THEME_COLOR,
};

// Root metadata for every locale page. Sets the title TEMPLATE ("<page> | Brand")
// + site defaults; individual pages override title/description/canonical via
// their own generateMetadata (see @/shared/lib/seo). Icons + manifest are wired
// once here so the whole site inherits them.
export async function generateMetadata({ params }) {
  const { lng } = await params;
  const base = buildMetadata({ lng, page: 'site', path: '/' });
  // Optional search-engine ownership verification — set these in the deploy env
  // once you claim the site in Google Search Console / Bing Webmaster Tools.
  const googleVerification = process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION;
  const bingVerification = process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION;
  const verification = {
    ...(googleVerification ? { google: googleVerification } : {}),
    ...(bingVerification ? { other: { 'msvalidate.01': bingVerification } } : {}),
  };
  return {
    ...base,
    title: {
      default: base.title?.absolute ?? base.title,
      template: `%s | ${brand(lng)}`,
    },
    applicationName: brand(lng),
    manifest: '/manifest.webmanifest',
    ...(Object.keys(verification).length ? { verification } : {}),
    // Favicon / icon links are auto-generated by Next from the file-convention
    // assets in app/: favicon.ico, icon.png and apple-icon.png (all derived
    // from the brand logo's owl mascot).
  };
}

// Root layout for every page. The active locale comes from the [lng] URL
// segment; Ayah uses one stable light/green theme across marketing and dashboard.
export default async function LocaleLayout({ children, params }) {
  const { lng } = await params;
  if (!languages.includes(lng)) notFound();

  const dir = getDirection(lng);

  return (
    <html lang={lng} dir={dir} suppressHydrationWarning>
      <body className={cairo.variable}>
        {/* Site-wide structured data: who we are + the site/languages. */}
        <JsonLd data={[organizationSchema(lng), websiteSchema(lng)]} />
        {/* AppProviders: i18n -> fixed theme (RTL cache) -> auth -> feedback */}
        <AppProviders lng={lng}>
          {children}
          <WhatsAppButton />
        </AppProviders>
      </body>
    </html>
  );
}
