"use client";

import { useTranslation } from "../../../i18n/client.js";

export const invoicesText = {
  ar: {
    // dialog
    invoice: "الفاتورة",
    invoiceFor: "فاتورة الاشتراك",
    noInvoice: "لا توجد فاتورة لهذا الاشتراك بعد.",
    generate: "إنشاء الفاتورة",
    regenerate: "إعادة توليد الفاتورة",
    regenerateHint:
      "يعيد ضبط الفاتورة بالكامل من القالب والاشتراك (المبالغ، الملاحظات، تعليمات الدفع، فترة الفوترة والتواريخ) ويصفّر الرصيد/المديونية السابقة.",
    edit: "تعديل",
    print: "طباعة",
    markPaid: "تأكيد الدفع",
    requestPayment: "مطالبة بالسداد",
    resendPayment: "إعادة المطالبة",
    requestPaymentConfirm:
      "سيتم إظهار الفاتورة لولي الأمر وإرسال إشعار له بالمطالبة بالسداد. هل تريد المتابعة؟",
    paymentRequested: "تم إرسال المطالبة",
    close: "إغلاق",
    // document
    invoiceTitle: "فاتورة مطالبة",
    invoiceNumber: "رقم الفاتورة",
    issueDate: "تاريخ الإصدار",
    dueDate: "تاريخ الاستحقاق",
    billingPeriod: "فترة الفوترة",
    MONTHLY: "شهري",
    YEARLY: "سنوي",
    status: "الحالة",
    billTo: "إلى",
    student: "الطالب",
    guardian: "ولي الأمر",
    phone: "الهاتف",
    email: "البريد",
    plan: "الباقة",
    description: "البيان",
    hours: "عدد الساعات",
    freeHours: "ساعات مجانية",
    hourlyRate: "سعر الساعة",
    amount: "المبلغ",
    subtotal: "الإجمالي الفرعي",
    originalPrice: "السعر قبل الخصم",
    discount: "خصم",
    transferFee: "رسوم التحويل",
    previousCredit: "رصيد سابق (دائن)",
    previousDebt: "مديونية سابقة",
    total: "الإجمالي المستحق",
    notesTitle: "ملاحظات هامة",
    paymentInstructionsTitle: "تعليمات الدفع",
    // statuses
    UNPAID: "غير مدفوعة",
    PAID: "مدفوعة",
    VOID: "ملغاة",
    // edit form
    editTitle: "تعديل الفاتورة",
    companyName: "اسم الجهة",
    companyAddress: "العنوان",
    companyPhone: "هاتف الجهة",
    companyEmail: "بريد الجهة",
    headerColor: "خلفية الترويسة",
    headerTextColor: "نص الترويسة",
    accentColor: "اللون المميّز",
    textColor: "لون النص",
    notesColor: "لون الملاحظات",
    paymentInstructionsColor: "لون تعليمات الدفع",
    transferFeePercent: "رسوم التحويل (%)",
    transferFeeFixed: "رسوم تحويل ثابتة",
    notes: "ملاحظات الفاتورة",
    notesArLabel: "ملاحظات الفاتورة (عربي)",
    notesEnLabel: "ملاحظات الفاتورة (إنجليزي)",
    notesHint: "كل سطر = ملاحظة. اتركها فارغة لإزالة كل الملاحظات.",
    paymentInstructionsArLabel: "تعليمات الدفع (عربي)",
    paymentInstructionsEnLabel: "تعليمات الدفع (إنجليزي)",
    downloadPdf: "تنزيل PDF",
    paymentStatus: "حالة السداد",
    save: "حفظ",
    cancel: "إلغاء",
    hoursLocked: "عدد الساعات والمبلغ يأتيان من الاشتراك ولا يمكن تعديلهما.",
    // mark paid flow
    markPaidConfirm: "هل تريد تأكيد دفع هذه الفاتورة؟",
    activateConfirm:
      "تم تأكيد الدفع. هل تريد تفعيل الاشتراك الآن؟ (نعم = تفعيل فوري، لا = إبقاء الاشتراك كما هو)",
  },
  en: {
    invoice: "Invoice",
    invoiceFor: "Subscription invoice",
    noInvoice: "No invoice has been created for this subscription yet.",
    generate: "Generate invoice",
    regenerate: "Regenerate invoice",
    regenerateHint:
      "Fully resets the invoice from the template and subscription (amounts, notes, payment instructions, billing period and dates) and clears previous credit/debt.",
    edit: "Edit",
    print: "Print",
    markPaid: "Mark as paid",
    requestPayment: "Request payment",
    resendPayment: "Resend request",
    requestPaymentConfirm:
      "This will show the invoice to the guardian and send them a notification requesting payment. Continue?",
    paymentRequested: "Payment requested",
    close: "Close",
    invoiceTitle: "Demand Invoice",
    invoiceNumber: "Invoice #",
    issueDate: "Issue date",
    dueDate: "Due date",
    billingPeriod: "Billing period",
    MONTHLY: "Monthly",
    YEARLY: "Yearly",
    status: "Status",
    billTo: "Bill to",
    student: "Student",
    guardian: "Guardian",
    phone: "Phone",
    email: "Email",
    plan: "Plan",
    description: "Description",
    hours: "Hours",
    freeHours: "Free hours",
    hourlyRate: "Hourly rate",
    amount: "Amount",
    subtotal: "Subtotal",
    originalPrice: "Original price",
    discount: "Discount",
    transferFee: "Transfer fee",
    previousCredit: "Previous credit",
    previousDebt: "Previous debt",
    total: "Total due",
    notesTitle: "Important notes",
    paymentInstructionsTitle: "Payment instructions",
    UNPAID: "Unpaid",
    PAID: "Paid",
    VOID: "Void",
    editTitle: "Edit invoice",
    companyName: "Company name",
    companyAddress: "Address",
    companyPhone: "Company phone",
    companyEmail: "Company email",
    headerColor: "Header background",
    headerTextColor: "Header text",
    accentColor: "Accent color",
    textColor: "Text color",
    notesColor: "Notes color",
    paymentInstructionsColor: "Payment instructions color",
    transferFeePercent: "Transfer fee (%)",
    transferFeeFixed: "Fixed transfer fee",
    notes: "Invoice notes",
    notesArLabel: "Invoice notes (Arabic)",
    notesEnLabel: "Invoice notes (English)",
    notesHint: "One note per line. Leave empty to remove all notes.",
    paymentInstructionsArLabel: "Payment instructions (Arabic)",
    paymentInstructionsEnLabel: "Payment instructions (English)",
    downloadPdf: "Download PDF",
    paymentStatus: "Payment",
    save: "Save",
    cancel: "Cancel",
    hoursLocked: "Hours and amount come from the subscription and can't be edited.",
    markPaidConfirm: "Mark this invoice as paid?",
    activateConfirm:
      "Payment confirmed. Activate the subscription now? (Yes = activate immediately, No = leave the subscription unchanged)",
  },
};

export function useInvoicesText() {
  const { lng } = useTranslation();
  return invoicesText[lng === "en" ? "en" : "ar"];
}
