"use client";

import { useTranslation } from "../../../i18n/client.js";

export const invoicesText = {
  ar: {
    // dialog
    invoice: "الفاتورة",
    invoiceFor: "فاتورة الاشتراك",
    noInvoice: "لا توجد فاتورة لهذا الاشتراك بعد.",
    generate: "إنشاء الفاتورة",
    regenerate: "إعادة توليد الفاتورة",
    regenerateHint: "يعيد سحب آخر إعدادات القالب ويعيد حساب المبالغ.",
    edit: "تعديل",
    print: "طباعة",
    markPaid: "تأكيد الدفع",
    close: "إغلاق",
    // document
    invoiceTitle: "فاتورة مطالبة",
    invoiceNumber: "رقم الفاتورة",
    issueDate: "تاريخ الإصدار",
    dueDate: "تاريخ الاستحقاق",
    billingPeriod: "فترة الفوترة",
    status: "الحالة",
    billTo: "إلى",
    student: "الطالب",
    guardian: "ولي الأمر",
    phone: "الهاتف",
    email: "البريد",
    plan: "الباقة",
    description: "البيان",
    hours: "عدد الساعات",
    freeHours: "ساعات مجانية",
    hourlyRate: "سعر الساعة",
    amount: "المبلغ",
    subtotal: "الإجمالي الفرعي",
    transferFee: "رسوم التحويل",
    previousCredit: "رصيد سابق (دائن)",
    previousDebt: "مديونية سابقة",
    total: "الإجمالي المستحق",
    notesTitle: "ملاحظات هامة",
    // statuses
    UNPAID: "غير مدفوعة",
    PAID: "مدفوعة",
    VOID: "ملغاة",
    // edit form
    editTitle: "تعديل الفاتورة",
    companyName: "اسم الجهة",
    companyAddress: "العنوان",
    companyPhone: "هاتف الجهة",
    companyEmail: "بريد الجهة",
    headerColor: "لون الترويسة",
    accentColor: "اللون المميّز",
    transferFeePercent: "رسوم التحويل (%)",
    transferFeeFixed: "رسوم تحويل ثابتة",
    notes: "ملاحظات الفاتورة",
    save: "حفظ",
    cancel: "إلغاء",
    hoursLocked: "عدد الساعات والمبلغ يأتيان من الاشتراك ولا يمكن تعديلهما.",
    // mark paid flow
    markPaidConfirm: "هل تريد تأكيد دفع هذه الفاتورة؟",
    activateConfirm:
      "تم تأكيد الدفع. هل تريد تفعيل الاشتراك الآن؟ (نعم = تفعيل فوري، لا = إبقاء الاشتراك كما هو)",
  },
  en: {
    invoice: "Invoice",
    invoiceFor: "Subscription invoice",
    noInvoice: "No invoice has been created for this subscription yet.",
    generate: "Generate invoice",
    regenerate: "Regenerate invoice",
    regenerateHint: "Re-pulls the latest template settings and recomputes amounts.",
    edit: "Edit",
    print: "Print",
    markPaid: "Mark as paid",
    close: "Close",
    invoiceTitle: "Demand Invoice",
    invoiceNumber: "Invoice #",
    issueDate: "Issue date",
    dueDate: "Due date",
    billingPeriod: "Billing period",
    status: "Status",
    billTo: "Bill to",
    student: "Student",
    guardian: "Guardian",
    phone: "Phone",
    email: "Email",
    plan: "Plan",
    description: "Description",
    hours: "Hours",
    freeHours: "Free hours",
    hourlyRate: "Hourly rate",
    amount: "Amount",
    subtotal: "Subtotal",
    transferFee: "Transfer fee",
    previousCredit: "Previous credit",
    previousDebt: "Previous debt",
    total: "Total due",
    notesTitle: "Important notes",
    UNPAID: "Unpaid",
    PAID: "Paid",
    VOID: "Void",
    editTitle: "Edit invoice",
    companyName: "Company name",
    companyAddress: "Address",
    companyPhone: "Company phone",
    companyEmail: "Company email",
    headerColor: "Header color",
    accentColor: "Accent color",
    transferFeePercent: "Transfer fee (%)",
    transferFeeFixed: "Fixed transfer fee",
    notes: "Invoice notes",
    save: "Save",
    cancel: "Cancel",
    hoursLocked: "Hours and amount come from the subscription and can't be edited.",
    markPaidConfirm: "Mark this invoice as paid?",
    activateConfirm:
      "Payment confirmed. Activate the subscription now? (Yes = activate immediately, No = leave the subscription unchanged)",
  },
};

export function useInvoicesText() {
  const { lng } = useTranslation();
  return invoicesText[lng === "en" ? "en" : "ar"];
}
