// Full certificate-template projection (all copy + style fields).
export const certificateTemplateSelect = {
  id: true,
  key: true,
  nameAr: true,
  nameEn: true,
  headingAr: true,
  headingEn: true,
  introAr: true,
  introEn: true,
  bodyAr: true,
  bodyEn: true,
  congratsAr: true,
  congratsEn: true,
  thanksAr: true,
  thanksEn: true,
  signatureName: true,
  signatureTitleAr: true,
  signatureTitleEn: true,
  themeJson: true,
  isActive: true,
  isDefault: true,
  createdAt: true,
  updatedAt: true,
};
