"use client";

import { useTranslation } from "../../../i18n/client.js";

export const sessionsText = {
  ar: {
    pageTitle: "الجلسات",
    pageDescription: "جدوِل جلسات الطلاب وأدِر مواعيدها وحالتها.",
    create: "جلسة جديدة",
    edit: "تعديل",
    delete: "حذف",
    actions: "إجراءات",
    // columns
    student: "الطالب",
    title: "العنوان",
    startsAt: "يبدأ في",
    endsAt: "ينتهي في",
    status: "الحالة",
    meetingLink: "رابط الجلسة",
    join: "انضمام",
    // statuses
    SCHEDULED: "مجدوَلة",
    COMPLETED: "مكتملة",
    CANCELLED: "ملغاة",
    MISSED: "فائتة",
    // form
    studentField: "الطالب",
    selectStudent: "اختر الطالب",
    titleField: "عنوان الجلسة",
    startsAtField: "وقت البداية",
    endsAtField: "وقت النهاية",
    statusField: "الحالة",
    meetingLinkField: "رابط الاجتماع",
    subscriptionIdField: "رقم الاشتراك (اختياري)",
    notesField: "ملاحظات",
    required: "هذا الحقل مطلوب",
    save: "حفظ",
    cancel: "إلغاء",
    createTitle: "إنشاء جلسة جديدة",
    editTitle: "تعديل الجلسة",
    deleteConfirm: "هل تريد حذف هذه الجلسة؟",
    empty: "لا توجد جلسات بعد.",
    noTitle: "بدون عنوان",
    loadingStudents: "جارٍ تحميل الطلاب...",
    // plan section
    planTitle: "خطة المرة الجاية",
    planOptional: "الخطة اختيارية — أضف تكليفاً واحداً على الأقل أو واجباً لحفظها.",
    loadingSurahs: "جارٍ تحميل السور...",
    memorizeSection: "حفظ",
    reviewSection: "مراجعة",
    addMemorize: "أضف سورة للحفظ",
    addReview: "أضف سورة للمراجعة",
    surahLabel: "السورة",
    surahRequired: "اختر السورة",
    wholeSurah: "كل السورة",
    wholeSurahToggle: "تبديل بين كل السورة ونطاق الآيات",
    fromAyah: "من آية",
    toAyah: "إلى آية",
    ayahRequired: "أدخل رقم الآية",
    ayahMin: "الآية لا تقل عن 1",
    ayahMax: "الآية لا تتجاوز",
    fromExceedsTo: "آية البداية يجب أن تكون ≤ آية النهاية",
    removeRow: "حذف",
    noRows: "لا يوجد تكليف، اضغط + للإضافة.",
    homeworkLabel: "واجب",
  },
  en: {
    pageTitle: "Sessions",
    pageDescription: "Schedule student sessions and manage their times and status.",
    create: "New session",
    edit: "Edit",
    delete: "Delete",
    actions: "Actions",
    student: "Student",
    title: "Title",
    startsAt: "Starts",
    endsAt: "Ends",
    status: "Status",
    meetingLink: "Meeting link",
    join: "Join",
    SCHEDULED: "Scheduled",
    COMPLETED: "Completed",
    CANCELLED: "Cancelled",
    MISSED: "Missed",
    studentField: "Student",
    selectStudent: "Select a student",
    titleField: "Session title",
    startsAtField: "Start time",
    endsAtField: "End time",
    statusField: "Status",
    meetingLinkField: "Meeting link",
    subscriptionIdField: "Subscription ID (optional)",
    notesField: "Notes",
    required: "This field is required",
    save: "Save",
    cancel: "Cancel",
    createTitle: "Create a new session",
    editTitle: "Edit session",
    deleteConfirm: "Delete this session?",
    empty: "No sessions yet.",
    noTitle: "Untitled",
    loadingStudents: "Loading students...",
    // plan section
    planTitle: "Next-time plan",
    planOptional: "The plan is optional — add at least one assignment or a homework note to save it.",
    loadingSurahs: "Loading surahs...",
    memorizeSection: "Memorization (حفظ)",
    reviewSection: "Review (مراجعة)",
    addMemorize: "Add surah to memorize",
    addReview: "Add surah to review",
    surahLabel: "Surah",
    surahRequired: "Choose a surah",
    wholeSurah: "Whole surah",
    wholeSurahToggle: "Toggle between whole surah and ayah range",
    fromAyah: "From ayah",
    toAyah: "To ayah",
    ayahRequired: "Enter ayah number",
    ayahMin: "Ayah must be at least 1",
    ayahMax: "Ayah must not exceed",
    fromExceedsTo: "Start ayah must be ≤ end ayah",
    removeRow: "Remove",
    noRows: "No assignments yet, press + to add.",
    homeworkLabel: "Homework",
  },
};

export function useSessionsText() {
  const { lng } = useTranslation();
  return sessionsText[lng === "en" ? "en" : "ar"];
}
