"use client";

import { useTranslation } from "../../../i18n/client.js";

export const plansText = {
  ar: {
    pageTitle: "الخطط والباقات",
    pageDescription: "أنشئ وعدّل خطط الاشتراك وأسعارها وخصوماتها.",
    create: "خطة جديدة",
    edit: "تعديل",
    delete: "حذف",
    discounts: "الخصومات",
    title: "الاسم",
    period: "الدورة",
    hours: "الساعات",
    price: "السعر",
    rate: "سعر الساعة",
    featured: "مميّزة",
    active: "مُفعّلة",
    actions: "إجراءات",
    monthly: "شهري",
    yearly: "سنوي",
    yes: "نعم",
    no: "لا",
    // form
    titleAr: "الاسم (عربي)",
    titleEn: "الاسم (إنجليزي)",
    descriptionAr: "الوصف (عربي)",
    descriptionEn: "الوصف (إنجليزي)",
    billingPeriod: "دورة الفوترة",
    hourlyRate: "سعر الساعة (£)",
    sortOrder: "الترتيب",
    isFeatured: "خطة مميّزة",
    isActive: "مُفعّلة",
    required: "هذا الحقل مطلوب",
    save: "حفظ",
    cancel: "إلغاء",
    createTitle: "إنشاء خطة جديدة",
    editTitle: "تعديل الخطة",
    deleteConfirm: "هل تريد إلغاء تفعيل هذه الخطة؟",
    // discounts
    discountsFor: "خصومات الخطة",
    addDiscount: "إضافة خصم",
    type: "النوع",
    value: "القيمة",
    constraint: "القيد",
    percent: "نسبة %",
    fixed: "مبلغ ثابت",
    count: "عدد مرّات",
    duration: "مدة",
    noDiscounts: "لا توجد خصومات بعد",
    empty: "لا توجد خطط بعد — ابدأ بإنشاء خطة.",
  },
  en: {
    pageTitle: "Plans & Packages",
    pageDescription: "Create and edit subscription plans, pricing and discounts.",
    create: "New plan",
    edit: "Edit",
    delete: "Delete",
    discounts: "Discounts",
    title: "Name",
    period: "Period",
    hours: "Hours",
    price: "Price",
    rate: "Hourly rate",
    featured: "Featured",
    active: "Active",
    actions: "Actions",
    monthly: "Monthly",
    yearly: "Yearly",
    yes: "Yes",
    no: "No",
    titleAr: "Name (Arabic)",
    titleEn: "Name (English)",
    descriptionAr: "Description (Arabic)",
    descriptionEn: "Description (English)",
    billingPeriod: "Billing period",
    hourlyRate: "Hourly rate (£)",
    sortOrder: "Sort order",
    isFeatured: "Featured plan",
    isActive: "Active",
    required: "This field is required",
    save: "Save",
    cancel: "Cancel",
    createTitle: "Create a new plan",
    editTitle: "Edit plan",
    deleteConfirm: "Deactivate this plan?",
    discountsFor: "Plan discounts",
    addDiscount: "Add discount",
    type: "Type",
    value: "Value",
    constraint: "Constraint",
    percent: "Percent %",
    fixed: "Fixed amount",
    count: "Count",
    duration: "Duration",
    noDiscounts: "No discounts yet",
    empty: "No plans yet — start by creating one.",
  },
};

export function usePlansText() {
  const { lng } = useTranslation();
  return plansText[lng === "en" ? "en" : "ar"];
}
