"use client";

import { useTranslation } from "../../../i18n/client.js";

export const plansText = {
  ar: {
    pageTitle: "الخطط والباقات",
    pageDescription: "أنشئ وعدّل خطط الاشتراك وأسعارها وخصوماتها.",
    create: "خطة جديدة",
    edit: "تعديل",
    delete: "حذف",
    discounts: "الخصومات",
    title: "الاسم",
    period: "الدورة",
    hours: "الساعات",
    price: "السعر",
    rate: "سعر الساعة",
    featured: "مميّزة",
    active: "مُفعّلة",
    actions: "إجراءات",
    monthly: "شهري",
    yearly: "سنوي",
    both: "كلاهما",
    yes: "نعم",
    no: "لا",
    perMonth: "/ شهر",
    perYear: "/ سنة",
    // form
    titleAr: "الاسم (عربي)",
    titleEn: "الاسم (إنجليزي)",
    descriptionAr: "الوصف (عربي)",
    descriptionEn: "الوصف (إنجليزي)",
    hourlyRate: "سعر الساعة",
    hoursHint: "عدد الساعات فقط. السعر يُحسب تلقائيًا من سعر الساعة في الإعدادات.",
    priceHint: "يُحسب تلقائيًا من الساعات × سعر الساعة في الإعدادات.",
    sortOrder: "الترتيب",
    isFeatured: "خطة مميّزة",
    isActive: "مُفعّلة",
    required: "هذا الحقل مطلوب",
    save: "حفظ",
    cancel: "إلغاء",
    createTitle: "إنشاء خطة جديدة",
    editTitle: "تعديل الخطة",
    deleteConfirm: "هل تريد إلغاء تفعيل هذه الخطة؟",
    // coupons / discounts
    discountsFor: "خصومات الخطة",
    addDiscount: "إضافة خصم",
    scope: "النطاق",
    type: "النوع",
    value: "القيمة",
    code: "الكود",
    codeHint: "اتركه فارغًا لتوليد كود تلقائيًا.",
    generate: "توليد",
    startsAt: "يبدأ في",
    endsAt: "ينتهي في",
    validity: "الصلاحية",
    maxRedemptions: "أقصى عدد استخدامات",
    redemptions: "الاستخدام",
    percent: "نسبة %",
    fixed: "مبلغ ثابت",
    noDiscounts: "لا توجد خصومات بعد",
    unlimited: "غير محدود",
    deleteCouponConfirm: "هل تريد تعطيل هذا الخصم؟ سيظل موجودًا في صفحة الأكواد ضمن المعطّلة.",
    enableCouponConfirm: "هل تريد إعادة تفعيل هذا الخصم؟",
    status: "الحالة",
    enabled: "شغّال",
    disabled: "معطّل",
    enable: "تفعيل",
    disable: "تعطيل",
    all: "الكل",
    empty: "لا توجد خطط بعد — ابدأ بإنشاء خطة.",
  },
  en: {
    pageTitle: "Plans & Packages",
    pageDescription: "Create and edit subscription plans, pricing and discounts.",
    create: "New plan",
    edit: "Edit",
    delete: "Delete",
    discounts: "Discounts",
    title: "Name",
    period: "Period",
    hours: "Hours",
    price: "Price",
    rate: "Hourly rate",
    featured: "Featured",
    active: "Active",
    actions: "Actions",
    monthly: "Monthly",
    yearly: "Yearly",
    both: "Both",
    yes: "Yes",
    no: "No",
    perMonth: "/ mo",
    perYear: "/ yr",
    titleAr: "Name (Arabic)",
    titleEn: "Name (English)",
    descriptionAr: "Description (Arabic)",
    descriptionEn: "Description (English)",
    hourlyRate: "Hourly rate",
    hoursHint: "Hours only. The price is computed from the hourly rate in Settings.",
    priceHint: "Computed automatically from hours × the hourly rate in Settings.",
    sortOrder: "Sort order",
    isFeatured: "Featured plan",
    isActive: "Active",
    required: "This field is required",
    save: "Save",
    cancel: "Cancel",
    createTitle: "Create a new plan",
    editTitle: "Edit plan",
    deleteConfirm: "Deactivate this plan?",
    discountsFor: "Plan discounts",
    addDiscount: "Add discount",
    scope: "Scope",
    type: "Type",
    value: "Value",
    code: "Code",
    codeHint: "Leave empty to auto-generate a code.",
    generate: "Generate",
    startsAt: "Starts at",
    endsAt: "Ends at",
    validity: "Validity",
    maxRedemptions: "Max redemptions",
    redemptions: "Redemptions",
    percent: "Percent %",
    fixed: "Fixed amount",
    noDiscounts: "No discounts yet",
    unlimited: "Unlimited",
    deleteCouponConfirm: "Disable this discount? It stays on the Coupons page under Disabled.",
    enableCouponConfirm: "Re-enable this discount?",
    status: "Status",
    enabled: "Active",
    disabled: "Disabled",
    enable: "Enable",
    disable: "Disable",
    all: "All",
    empty: "No plans yet — start by creating one.",
  },
};

export function usePlansText() {
  const { lng } = useTranslation();
  return plansText[lng === "en" ? "en" : "ar"];
}
