"use client";

import { useTranslation } from "../../../i18n/client.js";

export const certificatesText = {
  ar: {
    pageTitle: "الشهادات",
    pageDescription: "شهادات الإنجاز الخاصة بك",
    empty: "لا توجد شهادات بعد",
    title: "العنوان",
    student: "الطالب",
    type: "النوع",
    issuedAt: "تاريخ الإصدار",
    view: "عرض",
    close: "إغلاق",
    print: "طباعة",
    certificateOf: "شهادة تقدير",
    awardedTo: "تُمنح هذه الشهادة إلى",
    forText: "تقديرًا لـ",
    issuedOn: "صدرت بتاريخ",
    loading: "جارٍ التحميل...",
    // academy brand (shown on every certificate)
    academyName: "أكاديمية آية لتعليم القرآن",
    academyTagline: "نتعلّم القرآن والأخلاق باللعب",
    signatureLabel: "التوقيع",
    defaultSignature: "إدارة الأكاديمية",
    sealText: "معتمدة",
    typeGame: "لعبة",
    typeQuiz: "اختبار",
    typeManual: "يدوي",
    typeCustom: "مخصّص",
    examTitle: "شهادة اجتياز الاختبار",
    // create flow
    create: "إنشاء شهادة",
    createTitle: "إنشاء شهادة جديدة",
    save: "حفظ",
    cancel: "إلغاء",
    required: "هذا الحقل مطلوب",
    titleRequired: "أدخل العنوان بالعربية أو الإنجليزية على الأقل",
    studentLabel: "الطالب",
    studentPlaceholder: "اختر طالبًا",
    titleArLabel: "العنوان (بالعربية)",
    titleEnLabel: "العنوان (بالإنجليزية)",
    bodyArLabel: "نص الشهادة (بالعربية)",
    bodyEnLabel: "نص الشهادة (بالإنجليزية)",
    subtitleArLabel: "سطر فرعي (بالعربية)",
    subtitleEnLabel: "سطر فرعي (بالإنجليزية)",
    templateLabel: "التصميم",
    fontLabel: "نمط الخط",
    accentLabel: "اللون الأساسي",
    backgroundLabel: "لون الخلفية",
    presetsLabel: "ألوان جاهزة",
    emojiLabel: "رمز تعبيري (اختياري)",
    signatureFieldLabel: "اسم الموقِّع",
    sealToggleLabel: "إظهار خاتم الاعتماد",
    previewLabel: "معاينة مباشرة",
    sectionContent: "محتوى الشهادة",
    sectionStyle: "الشكل والتصميم",
    sectionLayout: "التخطيط",
    sectionBranding: "العلامة والشعار",
    sectionFooter: "التذييل والاعتماد",
    // layout / branding / style settings
    orientationLabel: "اتجاه الشهادة",
    orientationLandscape: "أفقي",
    orientationPortrait: "عمودي",
    secondaryLabel: "اللون الثانوي",
    borderStyleLabel: "نمط الإطار",
    borderFoil: "مزدوج (افتراضي)",
    borderDouble: "خطّان",
    borderSimple: "بسيط",
    borderNone: "بدون إطار",
    nameScaleLabel: "حجم الاسم",
    logoSizeLabel: "حجم الشعار",
    logoSizeSm: "صغير",
    logoSizeMd: "متوسط",
    logoSizeLg: "كبير",
    showWatermarkLabel: "إظهار الشعار المائي",
    watermarkOpacityLabel: "شفافية الشعار المائي",
    showTaglineLabel: "إظهار شعار الأكاديمية",
    showDateLabel: "إظهار تاريخ الإصدار",
    sealTextLabel: "نص الخاتم",
    signatureTitleLabel: "صفة الموقِّع",
    autoLogoNote: "يُضاف شعار الأكاديمية تلقائيًا إلى كل شهادة (في الترويسة وكعلامة مائية).",
    // template names
    elegant: "أنيق",
    geometric: "زخرفة إسلامية",
    classic: "كلاسيكي",
    stars: "نجوم",
    rainbow: "قوس قزح",
    crescent: "هلال",
    balloons: "بالونات",
    badges: "أوسمة",
    EXAM: "اختبار (موحّد)",
    // font styles
    fontElegant: "أنيق (مزخرف)",
    fontClassic: "كلاسيكي",
    fontModern: "عصري",
  },
  en: {
    pageTitle: "Certificates",
    pageDescription: "Your achievement certificates",
    empty: "No certificates yet",
    title: "Title",
    student: "Student",
    type: "Type",
    issuedAt: "Issued",
    view: "View",
    close: "Close",
    print: "Print",
    certificateOf: "Certificate of Achievement",
    awardedTo: "This certificate is proudly awarded to",
    forText: "in recognition of",
    issuedOn: "Issued on",
    loading: "Loading...",
    // academy brand (shown on every certificate)
    academyName: "Aya Academy for Quran",
    academyTagline: "Learning Quran & good manners through play",
    signatureLabel: "Signature",
    defaultSignature: "Academy Management",
    sealText: "Official",
    typeGame: "Game",
    typeQuiz: "Quiz",
    typeManual: "Manual",
    typeCustom: "Custom",
    examTitle: "Certificate of Exam Achievement",
    // create flow
    create: "Create certificate",
    createTitle: "Create a new certificate",
    save: "Save",
    cancel: "Cancel",
    required: "This field is required",
    titleRequired: "Enter a title in Arabic or English",
    studentLabel: "Student",
    studentPlaceholder: "Select a student",
    titleArLabel: "Title (Arabic)",
    titleEnLabel: "Title (English)",
    bodyArLabel: "Body text (Arabic)",
    bodyEnLabel: "Body text (English)",
    subtitleArLabel: "Subtitle (Arabic)",
    subtitleEnLabel: "Subtitle (English)",
    templateLabel: "Design",
    fontLabel: "Font style",
    accentLabel: "Accent color",
    backgroundLabel: "Background color",
    presetsLabel: "Quick colors",
    emojiLabel: "Emoji (optional)",
    signatureFieldLabel: "Signed by",
    sealToggleLabel: "Show official seal",
    previewLabel: "Live preview",
    sectionContent: "Certificate content",
    sectionStyle: "Look & design",
    sectionLayout: "Layout",
    sectionBranding: "Branding",
    sectionFooter: "Footer & seal",
    // layout / branding / style settings
    orientationLabel: "Orientation",
    orientationLandscape: "Landscape",
    orientationPortrait: "Portrait",
    secondaryLabel: "Secondary color",
    borderStyleLabel: "Border style",
    borderFoil: "Foil (default)",
    borderDouble: "Double",
    borderSimple: "Simple",
    borderNone: "No border",
    nameScaleLabel: "Name size",
    logoSizeLabel: "Logo size",
    logoSizeSm: "Small",
    logoSizeMd: "Medium",
    logoSizeLg: "Large",
    showWatermarkLabel: "Show watermark",
    watermarkOpacityLabel: "Watermark opacity",
    showTaglineLabel: "Show academy tagline",
    showDateLabel: "Show issue date",
    sealTextLabel: "Seal text",
    signatureTitleLabel: "Signature title",
    autoLogoNote: "The academy logo is added automatically to every certificate (header brand + watermark).",
    // template names
    elegant: "Elegant",
    geometric: "Islamic ornament",
    classic: "Classic",
    stars: "Stars",
    rainbow: "Rainbow",
    crescent: "Crescent",
    balloons: "Balloons",
    badges: "Badges",
    EXAM: "Exam (unified)",
    // font styles
    fontElegant: "Elegant (serif)",
    fontClassic: "Classic",
    fontModern: "Modern",
  },
};

export function useCertificatesText() {
  const { lng } = useTranslation();
  return certificatesText[lng === "en" ? "en" : "ar"];
}
