import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { MUIThemeProvider } from '@/providers/MUITheme';
import Navbar from '@/shared/ui/navigation/navbar';
import { cookies } from 'next/headers';
import { PageTheme } from '@/shared/types/general';
import ThemeTogglerProvider from '@/providers/ThemeToggler';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get('theme');
  const pageTheme: PageTheme = themeCookie?.value === 'dark' ? 'dark' : 'light';
  return (
    <html lang="en">
      <ThemeTogglerProvider defaultTheme={pageTheme}>
        <MUIThemeProvider pageTheme={pageTheme}>
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <Navbar />
            {children}
          </body>
        </MUIThemeProvider>
      </ThemeTogglerProvider>
    </html>
  );
}
