"use client";

// Feature-local bilingual strings for the dashboard shell + overviews.
import { useTranslation } from "../../../i18n/client.js";

export const dashboardText = {
  ar: {
    // shell
    appName: "أكاديمية آية",
    logout: "تسجيل الخروج",
    loading: "جارٍ التحميل...",
    menu: "القائمة",
    close: "إغلاق",
    // nav labels
    overview: "الرئيسية",
    users: "المستخدمون",
    plans: "الباقات",
    subscriptions: "الاشتراكات",
    paymentTemplate: "قالب الفاتورة",
    settings: "الإعدادات",
    coupons: "كوبونات الخصم",
    games: "الألعاب",
    myGames: "ألعابي",
    quizzes: "الاختبارات",
    quizBank: "بنك الأسئلة",
    invitations: "الدعوات",
    reports: "التقارير",
    sessionLog: "تسجيل الحصص",
    certificates: "الشهادات",
    certificateTemplates: "قوالب الشهادات",
    backups: "النسخ الاحتياطي",
    notifications: "الإشعارات",
    children: "الأبناء",
    badges: "الأوسمة",
    leaderboardNav: "لوحة الصدارة",
    userDetails: "تفاصيل المستخدم",
    // nav group headings
    navGroupPeople: "الأشخاص",
    navGroupBilling: "الاشتراكات والفواتير",
    navGroupActivities: "الألعاب والاختبارات",
    navGroupProgress: "التقدّم والتقدير",
    navGroupSystem: "النظام",
    navGroupChildren: "الأبناء",
    navGroupAccount: "الحساب",
    navGroupLearn: "التعلّم واللعب",
    navGroupAchievements: "إنجازاتي",
    // role labels
    roleAdmin: "معلّم",
    roleParent: "ولي أمر",
    roleStudent: "طالب",
    // overview greetings
    welcome: "مرحباً",
    welcomeAdmin: "لوحة تحكم المعلّم",
    welcomeParent: "لوحة ولي الأمر",
    welcomeStudent: "لوحتي",
    // admin cards
    users: "المستخدمون",
    students: "الطلاب",
    parents: "أولياء الأمور",
    revenue: "الإيرادات",
    subscriptionsByStatus: "الاشتراكات حسب الحالة",
    leaderboard: "لوحة المتصدرين",
    recentCertificates: "أحدث الشهادات",
    points: "نقطة",
    level: "المستوى",
    rank: "الترتيب",
    // parent / student
    activeSubscription: "اشتراك نشط",
    noActiveSubscription: "لا يوجد اشتراك نشط",
    renewSubscription: "تجديد الاشتراك",
    inactiveChildNote: "اشتراك الطفل منتهي — جدّد ليشاهد تقدّمه ويلعب.",
    pendingChildNote: "اشتراك طفلك قيد المراجعة — في انتظار الدفع والتفعيل",
    viewSubscription: "عرض الاشتراك",
    noSubscriptionNote: "لا يوجد اشتراك بعد",
    remainingHours: "ساعة متبقية",
    recentReports: "أحدث التقارير",
    assignedGames: "الألعاب المسندة",
    myBadges: "أوسمتي",
    noData: "لا توجد بيانات بعد",
    points2: "النقاط",
    // overview extras (redesign)
    welcomeParentSub: "تابِع رحلة أطفالك مع القرآن في مكان واحد",
    welcomeStudentSub: "هيا نواصل التعلّم اليوم! 🌟",
    welcomeAdminSub: "نظرة سريعة على الأكاديمية اليوم",
    myChildren: "أطفالي",
    childrenCount: "الأطفال",
    totalPoints: "إجمالي النقاط",
    totalBadges: "الأوسمة",
    badgesLabel: "الأوسمة",
    activeSubsCount: "اشتراكات نشطة",
    viewDetails: "التفاصيل",
    noChildren: "لم تتم إضافة أطفال بعد",
    noChildrenSub: "سيظهر هنا تقدّم أطفالك بمجرد إضافتهم.",
    addFirstChild: "أضف طفلك الأول",
    choosePlan: "اختر باقة",
    levelProgress: "تقدّم المستوى",
    keepGoing: "واصل التميّز! 🌟",
    continueLearning: "تابع التعلّم",
    quickActions: "إجراءات سريعة",
    activeSubscriptions: "اشتراكات نشطة",
    expiringSoon: "تنتهي قريباً",
    totalCertificates: "الشهادات",
    gamesLabel: "الألعاب",
    quizzesLabel: "الاختبارات",
    // student redesign
    nextActivity: "هيا نلعب الآن!",
    nextActivitySub: "لعبتك التالية في انتظارك 🎮",
    playNow: "العب الآن",
    allDoneTitle: "أحسنت! أنهيت كل ألعابك 🎉",
    allDoneSub: "تصفّح كل الألعاب وواصل التعلّم",
    browseGames: "تصفّح الألعاب",
    myAchievements: "إنجازاتي",
    competition: "المسابقة",
    yourRank: "ترتيبك",
    you: "أنت",
    weeklyChampions: "أبطال الأسبوع",
    seeFullBoard: "اللوحة كاملة",
    points3: "نقطة",
    badgesShort: "وسام",
    noBadgesYet: "ابدأ اللعب لتكسب أول وسام! 🏅",
    noCertsYet: "أكمل التحديات لتحصل على شهادتك الأولى 📜",
    noGamesYet: "لا توجد ألعاب مسندة بعد",
    keepLearning: "واصل التعلّم 🌟",
    // friendly game-status labels (replace the raw DB enum for the child)
    statusNew: "جديدة",
    statusInProgress: "نكمّلها",
    statusCompleted: "تمّت",
  },
  en: {
    appName: "Aya Academy",
    logout: "Log out",
    loading: "Loading...",
    menu: "Menu",
    close: "Close",
    overview: "Overview",
    users: "Users",
    plans: "Plans",
    subscriptions: "Subscriptions",
    paymentTemplate: "Invoice template",
    settings: "Settings",
    coupons: "Coupons",
    games: "Games",
    myGames: "My games",
    quizzes: "Quizzes",
    quizBank: "Question bank",
    invitations: "Invitations",
    reports: "Reports",
    sessionLog: "Session Log",
    certificates: "Certificates",
    certificateTemplates: "Certificate templates",
    backups: "Backups",
    notifications: "Notifications",
    children: "Children",
    badges: "Badges",
    leaderboardNav: "Leaderboard",
    userDetails: "User details",
    // nav group headings
    navGroupPeople: "People",
    navGroupBilling: "Billing",
    navGroupActivities: "Games & quizzes",
    navGroupProgress: "Progress & recognition",
    navGroupSystem: "System",
    navGroupChildren: "Children",
    navGroupAccount: "Account",
    navGroupLearn: "Learn & play",
    navGroupAchievements: "My achievements",
    roleAdmin: "Teacher",
    roleParent: "Parent",
    roleStudent: "Student",
    welcome: "Welcome",
    welcomeAdmin: "Teacher dashboard",
    welcomeParent: "Parent dashboard",
    welcomeStudent: "My dashboard",
    users: "Users",
    students: "Students",
    parents: "Parents",
    revenue: "Revenue",
    subscriptionsByStatus: "Subscriptions by status",
    leaderboard: "Leaderboard",
    recentCertificates: "Recent certificates",
    points: "pts",
    level: "Level",
    rank: "Rank",
    activeSubscription: "Active subscription",
    noActiveSubscription: "No active subscription",
    renewSubscription: "Renew subscription",
    inactiveChildNote: "This child's subscription has expired — renew to see progress and play.",
    pendingChildNote: "Your child's subscription is pending — awaiting payment & activation",
    viewSubscription: "View subscription",
    noSubscriptionNote: "No subscription yet",
    remainingHours: "hrs left",
    recentReports: "Recent reports",
    assignedGames: "Assigned games",
    myBadges: "My badges",
    noData: "No data yet",
    points2: "Points",
    // overview extras (redesign)
    welcomeParentSub: "Follow your children's Quran journey — all in one place",
    welcomeStudentSub: "Let's keep learning today! 🌟",
    welcomeAdminSub: "A quick look at the academy today",
    myChildren: "My children",
    childrenCount: "Children",
    totalPoints: "Total points",
    totalBadges: "Badges",
    badgesLabel: "Badges",
    activeSubsCount: "Active plans",
    viewDetails: "Details",
    noChildren: "No children added yet",
    noChildrenSub: "Your children's progress will appear here once they're added.",
    addFirstChild: "Add your first child",
    choosePlan: "Choose a plan",
    levelProgress: "Level progress",
    keepGoing: "Keep up the great work! 🌟",
    continueLearning: "Continue learning",
    quickActions: "Quick actions",
    activeSubscriptions: "Active subscriptions",
    expiringSoon: "Expiring soon",
    totalCertificates: "Certificates",
    gamesLabel: "Games",
    quizzesLabel: "Quizzes",
    // student redesign
    nextActivity: "Let's play now!",
    nextActivitySub: "Your next game is waiting 🎮",
    playNow: "Play now",
    allDoneTitle: "Awesome! You finished all your games 🎉",
    allDoneSub: "Browse all games and keep learning",
    browseGames: "Browse games",
    myAchievements: "My achievements",
    competition: "Competition",
    yourRank: "Your rank",
    you: "You",
    weeklyChampions: "This week's champions",
    seeFullBoard: "Full board",
    points3: "pts",
    badgesShort: "badges",
    noBadgesYet: "Start playing to earn your first badge! 🏅",
    noCertsYet: "Complete challenges to earn your first certificate 📜",
    noGamesYet: "No games assigned yet",
    keepLearning: "Keep learning 🌟",
    // friendly game-status labels (replace the raw DB enum for the child)
    statusNew: "New",
    statusInProgress: "Keep going",
    statusCompleted: "Done",
  },
};

export function useDashboardText() {
  const { lng } = useTranslation();
  return dashboardText[lng === "en" ? "en" : "ar"];
}
