"use client";

// Feature-local bilingual strings for the dashboard shell + overviews.
import { useTranslation } from "../../../i18n/client.js";

export const dashboardText = {
  ar: {
    // shell
    appName: "أكاديمية آية",
    logout: "تسجيل الخروج",
    loading: "جارٍ التحميل...",
    menu: "القائمة",
    close: "إغلاق",
    // nav labels
    overview: "الرئيسية",
    users: "المستخدمون",
    plans: "الباقات",
    subscriptions: "الاشتراكات",
    sessions: "الحصص",
    coupons: "كوبونات الخصم",
    games: "الألعاب",
    myGames: "ألعابي",
    quizzes: "الاختبارات",
    quizBank: "بنك الأسئلة",
    invitations: "الدعوات",
    reports: "التقارير",
    certificates: "الشهادات",
    backups: "النسخ الاحتياطي",
    notifications: "الإشعارات",
    children: "الأبناء",
    badges: "الأوسمة",
    leaderboardNav: "لوحة الصدارة",
    userDetails: "تفاصيل المستخدم",
    // role labels
    roleAdmin: "معلّم",
    roleParent: "ولي أمر",
    roleStudent: "طالب",
    // overview greetings
    welcome: "مرحباً",
    welcomeAdmin: "لوحة تحكم المعلّم",
    welcomeParent: "لوحة ولي الأمر",
    welcomeStudent: "لوحتي",
    // admin cards
    users: "المستخدمون",
    students: "الطلاب",
    parents: "أولياء الأمور",
    revenue: "الإيرادات",
    subscriptionsByStatus: "الاشتراكات حسب الحالة",
    leaderboard: "لوحة المتصدرين",
    recentCertificates: "أحدث الشهادات",
    points: "نقطة",
    level: "المستوى",
    rank: "الترتيب",
    // parent / student
    activeSubscription: "اشتراك نشط",
    noActiveSubscription: "لا يوجد اشتراك نشط",
    remainingHours: "ساعة متبقية",
    upcomingLessons: "الدروس القادمة",
    recentReports: "أحدث التقارير",
    assignedGames: "الألعاب المسندة",
    myBadges: "أوسمتي",
    joinLesson: "انضمام",
    noData: "لا توجد بيانات بعد",
    points2: "النقاط",
  },
  en: {
    appName: "Aya Academy",
    logout: "Log out",
    loading: "Loading...",
    menu: "Menu",
    close: "Close",
    overview: "Overview",
    users: "Users",
    plans: "Plans",
    subscriptions: "Subscriptions",
    sessions: "Sessions",
    coupons: "Coupons",
    games: "Games",
    myGames: "My games",
    quizzes: "Quizzes",
    quizBank: "Question bank",
    invitations: "Invitations",
    reports: "Reports",
    certificates: "Certificates",
    backups: "Backups",
    notifications: "Notifications",
    children: "Children",
    badges: "Badges",
    leaderboardNav: "Leaderboard",
    userDetails: "User details",
    roleAdmin: "Teacher",
    roleParent: "Parent",
    roleStudent: "Student",
    welcome: "Welcome",
    welcomeAdmin: "Teacher dashboard",
    welcomeParent: "Parent dashboard",
    welcomeStudent: "My dashboard",
    users: "Users",
    students: "Students",
    parents: "Parents",
    revenue: "Revenue",
    subscriptionsByStatus: "Subscriptions by status",
    leaderboard: "Leaderboard",
    recentCertificates: "Recent certificates",
    points: "pts",
    level: "Level",
    rank: "Rank",
    activeSubscription: "Active subscription",
    noActiveSubscription: "No active subscription",
    remainingHours: "hrs left",
    upcomingLessons: "Upcoming lessons",
    recentReports: "Recent reports",
    assignedGames: "Assigned games",
    myBadges: "My badges",
    joinLesson: "Join",
    noData: "No data yet",
    points2: "Points",
  },
};

export function useDashboardText() {
  const { lng } = useTranslation();
  return dashboardText[lng === "en" ? "en" : "ar"];
}
