"use client";

import { useTranslation } from "../../../i18n/client.js";

// Bilingual copy for the ADMIN games manager + per-game results screens.
// Mirrors the shape of plansText.js — Arabic default/RTL.
export const gamesAdminText = {
  ar: {
    // ── Games manager page ──
    pageTitle: "إدارة الألعاب",
    pageDescription: "تابع الألعاب، عيّنها للطلاب، واطّلع على نتائجهم.",
    title: "اللعبة",
    type: "النوع",
    public: "عام",
    private: "خاص",
    visibility: "الظهور",
    active: "مُفعّلة",
    inactive: "متوقّفة",
    passThreshold: "حد النجاح",
    freeGame: "اللعبة المجانية",
    freeGameChip: "اللعبة المجانية ★",
    setFree: "اجعلها المجانية",
    setFreeConfirm:
      "هل تريد جعل هذه اللعبة هي اللعبة المجانية الظاهرة في الصفحة الرئيسية؟ سيتم إلغاء أي لعبة مجانية أخرى، وستصبح هذه اللعبة عامة ومفعّلة.",
    actions: "إجراءات",
    assign: "تعيين",
    results: "النتائج",
    preview: "معاينة",
    // ── Badge linking ──
    badge: "الوسام",
    linkBadge: "ربط بوسام",
    noBadge: "بدون وسام",
    linkBadgeTitle: "ربط اللعبة بوسام",
    linkBadgeHint:
      "عند إكمال الطالب لهذه اللعبة بنجاح يحصل تلقائيًا على هذا الوسام ونقاطه.",
    currentBadge: "الوسام المرتبط حاليًا",
    searchBadge: "ابحث عن وسام بالاسم أو الكود…",
    noBadgesFound: "لا توجد أوسمة مطابقة.",
    points: "نقطة",
    link: "ربط",
    change: "تغيير",
    removeBadge: "إزالة الوسام",
    removeBadgeConfirm: "إزالة الوسام المرتبط بهذه اللعبة؟",
    loadingMore: "جارٍ تحميل المزيد…",
    // game types
    INTERACTIVE: "تفاعلية",
    QUIZ: "اختبار",
    STORY: "قصة",
    // ── Assign dialog ──
    assignTitle: "تعيين اللعبة",
    assignedStudents: "الطلاب المُعيَّنون",
    noAssigned: "لا يوجد طلاب مُعيَّنون بعد.",
    addStudents: "إضافة طلاب",
    noStudentsLeft: "تم تعيين جميع الطلاب.",
    dueAt: "تاريخ الاستحقاق (اختياري)",
    assignButton: "تعيين المحدّدين",
    unassign: "إلغاء التعيين",
    unassignConfirm: "إلغاء تعيين هذا الطالب من اللعبة؟",
    selectAtLeastOne: "اختر طالبًا واحدًا على الأقل.",
    loading: "جارٍ التحميل…",
    close: "إغلاق",
    // ── Results page ──
    resultsTitle: "نتائج اللعبة",
    backToGames: "العودة إلى الألعاب",
    totalAttempts: "إجمالي المحاولات",
    passedCount: "الناجحون",
    student: "الطالب",
    score: "النتيجة",
    correct: "الإجابات الصحيحة",
    passed: "ناجح",
    date: "التاريخ",
    pass: "ناجح",
    fail: "—",
    certificate: "الشهادة",
    noAttempts: "لا توجد محاولات بعد.",
    gameNotFound: "تعذّر العثور على اللعبة.",
  },
  en: {
    pageTitle: "Games Management",
    pageDescription: "Track games, assign them to students, and review results.",
    title: "Game",
    type: "Type",
    public: "Public",
    private: "Private",
    visibility: "Visibility",
    active: "Active",
    inactive: "Inactive",
    passThreshold: "Pass threshold",
    freeGame: "Free game",
    freeGameChip: "Free game ★",
    setFree: "Make it free",
    setFreeConfirm:
      "Make this the free game shown on the homepage? Any other free game will be cleared, and this game will become public and active.",
    actions: "Actions",
    assign: "Assign",
    results: "Results",
    preview: "Preview",
    // ── Badge linking ──
    badge: "Badge",
    linkBadge: "Link badge",
    noBadge: "No badge",
    linkBadgeTitle: "Link a badge to the game",
    linkBadgeHint:
      "When a student completes this game successfully, they automatically earn this badge and its points.",
    currentBadge: "Currently linked badge",
    searchBadge: "Search badges by name or code…",
    noBadgesFound: "No matching badges.",
    points: "pts",
    link: "Link",
    change: "Change",
    removeBadge: "Remove badge",
    removeBadgeConfirm: "Remove the badge linked to this game?",
    loadingMore: "Loading more…",
    INTERACTIVE: "Interactive",
    QUIZ: "Quiz",
    STORY: "Story",
    assignTitle: "Assign game",
    assignedStudents: "Assigned students",
    noAssigned: "No students assigned yet.",
    addStudents: "Add students",
    noStudentsLeft: "All students are already assigned.",
    dueAt: "Due date (optional)",
    assignButton: "Assign selected",
    unassign: "Unassign",
    unassignConfirm: "Unassign this student from the game?",
    selectAtLeastOne: "Select at least one student.",
    loading: "Loading…",
    close: "Close",
    resultsTitle: "Game results",
    backToGames: "Back to games",
    totalAttempts: "Total attempts",
    passedCount: "Passed",
    student: "Student",
    score: "Score",
    correct: "Correct",
    passed: "Passed",
    date: "Date",
    pass: "Passed",
    fail: "—",
    certificate: "Certificate",
    noAttempts: "No attempts yet.",
    gameNotFound: "Game not found.",
  },
};

export function useGamesAdminText() {
  const { lng } = useTranslation();
  return gamesAdminText[lng === "en" ? "en" : "ar"];
}
