"use client";

import { useTranslation } from "../../../i18n/client.js";

export const subscriptionsText = {
  ar: {
    pageTitle: "الاشتراكات",
    pageDescriptionAdmin:
      "راجع كل الاشتراكات، ووافق على الطلبات المعلّقة، وأنشئ اشتراكات يدوية.",
    pageDescriptionParent: "اشتراكات أبنائك وحالتها.",
    pageDescriptionStudent: "اشتراكاتك وحالتها.",
    create: "اشتراك يدوي",
    student: "الطالب",
    plan: "الخطة",
    status: "الحالة",
    price: "السعر",
    start: "البداية",
    end: "النهاية",
    hours: "الساعات",
    actions: "إجراءات",
    approve: "موافقة",
    reject: "رفض",
    cancelSubscription: "إلغاء الاشتراك",
    confirmCancel: "تأكيد إلغاء هذا الاشتراك؟",
    studentEmail: "ايميل الطالب",
    parents: "أولياء الأمور",
    parentPhone: "هاتف ولي الأمر",
    parentEmail: "ايميل ولي الأمر",
    // statuses
    PENDING: "بانتظار الموافقة",
    UPCOMING: "قادم",
    ACTIVE: "نشط",
    EXPIRED: "منتهٍ",
    CANCELLED: "ملغى",
    all: "الكل",
    // create dialog
    createTitle: "إنشاء اشتراك يدوي",
    selectStudent: "اختر الطالب",
    selectPlan: "اختر الخطة",
    startDate: "تاريخ البداية",
    endDate: "تاريخ النهاية",
    save: "حفظ",
    cancel: "إلغاء",
    required: "مطلوب",
    rejectTitle: "رفض الطلب",
    rejectReason: "سبب الرفض (اختياري)",
    confirmApprove: "تأكيد الموافقة على هذا الاشتراك؟",
    empty: "لا توجد اشتراكات بعد.",
  },
  en: {
    pageTitle: "Subscriptions",
    pageDescriptionAdmin:
      "Review every subscription, approve pending requests, and create manual ones.",
    pageDescriptionParent: "Your children's subscriptions and their status.",
    pageDescriptionStudent: "Your subscriptions and their status.",
    create: "Manual subscription",
    student: "Student",
    plan: "Plan",
    status: "Status",
    price: "Price",
    start: "Start",
    end: "End",
    hours: "Hours",
    actions: "Actions",
    approve: "Approve",
    reject: "Reject",
    cancelSubscription: "Cancel subscription",
    confirmCancel: "Cancel this subscription?",
    studentEmail: "Student email",
    parents: "Parents",
    parentPhone: "Parent phone",
    parentEmail: "Parent email",
    PENDING: "Pending approval",
    UPCOMING: "Upcoming",
    ACTIVE: "Active",
    EXPIRED: "Expired",
    CANCELLED: "Cancelled",
    all: "All",
    createTitle: "Create a manual subscription",
    selectStudent: "Select student",
    selectPlan: "Select plan",
    startDate: "Start date",
    endDate: "End date",
    save: "Save",
    cancel: "Cancel",
    required: "Required",
    rejectTitle: "Reject request",
    rejectReason: "Rejection reason (optional)",
    confirmApprove: "Approve this subscription?",
    empty: "No subscriptions yet.",
  },
};

export function useSubscriptionsText() {
  const { lng } = useTranslation();
  return subscriptionsText[lng === "en" ? "en" : "ar"];
}
