"use client";

import { useTranslation } from "../../../i18n/client.js";

export const subscriptionsText = {
  ar: {
    pageTitle: "الاشتراكات",
    view: "عرض",
    renew: "تجديد",
    renewTitle: "تجديد الاشتراك",
    renewSubmit: "تجديد",
    confirmRenewActive: "يوجد اشتراك فعّال لم ينتهِ بعد، هل تريد المتابعة؟",
    discount: "خصم",
    basePrice: "السعر قبل الخصم",
    netPrice: "السعر بعد الخصم",
    coupon: "الكوبون",
    pageDescriptionAdmin:
      "راجع كل الاشتراكات، ووافق على الطلبات المعلّقة، وأنشئ اشتراكات يدوية.",
    pageDescriptionParent: "اشتراكات أبنائك وحالتها.",
    pageDescriptionStudent: "اشتراكاتك وحالتها.",
    create: "اشتراك يدوي",
    student: "الطالب",
    allStudents: "كل الطلاب",
    plan: "الخطة",
    status: "الحالة",
    price: "السعر",
    start: "البداية",
    end: "النهاية",
    hours: "الساعات",
    actions: "إجراءات",
    approve: "موافقة",
    reject: "رفض",
    cancelSubscription: "إلغاء الاشتراك",
    confirmCancel: "تأكيد إلغاء هذا الاشتراك؟",
    studentEmail: "ايميل الطالب",
    parents: "أولياء الأمور",
    allParents: "كل أولياء الأمور",
    parentPhone: "هاتف ولي الأمر",
    parentEmail: "ايميل ولي الأمر",
    // statuses
    PENDING: "بانتظار الموافقة",
    UPCOMING: "قادم",
    ACTIVE: "نشط",
    EXPIRED: "منتهٍ",
    CANCELLED: "ملغى",
    all: "الكل",
    // create dialog
    createTitle: "إنشاء اشتراك يدوي",
    selectStudent: "اختر الطالب",
    selectPlan: "اختر الخطة",
    billingPeriod: "دورة الفوترة",
    monthly: "شهري",
    couponCode: "كود الكوبون (اختياري)",
    couponCodeHint: "لو فيه كوبون، اكتب الكود لربطه بالاشتراك وتطبيق الخصم.",
    priceCouponNote: "السعر هيتحسب بعد الخصم تلقائيًا عند الحفظ.",
    priceCharged: "السعر المحصّل",
    subsHours: "مدة الفاتورة",
    subsHoursHint: "الفاتورة بتتحسب على المدة دي",
    remainingHours: "المدة المتبقية",
    editHours: "تعديل المدة",
    editHoursTitle: "تعديل مدة الفاتورة",
    remainingHoursLabel: "الدقائق المتبقية",
    remainingHoursHint: "أدخل المدة المتبقية بالدقائق، مثل 45 أو 60 أو 90.",
    remainingExceedsSubs: "المدة المتبقية لا يمكن أن تتجاوز مدة الاشتراك.",
    remainingMinutesInvalid: "أدخل عدد دقائق صحيحًا.",
    startDate: "تاريخ البداية",
    endDate: "تاريخ النهاية",
    save: "حفظ",
    cancel: "إلغاء",
    required: "مطلوب",
    rejectTitle: "رفض الطلب",
    rejectReason: "سبب الرفض (اختياري)",
    confirmApprove: "تأكيد الموافقة على هذا الاشتراك؟",
    empty: "لا توجد اشتراكات بعد.",
    // usage-based billing
    phase: {
      accumulating: "بتتجمّع",
      awaitingPayment: "بانتظار الدفع",
      upcoming: "قادم",
      active: "نشط",
      ended: "منتهي",
    },
    origin: "النوع",
    originUsage: "حسب الحصص",
    originManual: "يدوي",
    accumulatingTitle: "فاتورة الشهر القادم (بتتجمّع)",
    liveHint: "بيتجمّع من حصص الشهر الحالي، ويتفوتر الشهر الجاي",
    frozenHint: "اتجمّد — جاهز للفاتورة",
    usageManagedHint: "بيتحسب تلقائياً من الحصص، ويتقفل آخر الشهر",
    currentTitle: "الاشتراك الحالي",
    noCurrent: "لا يوجد اشتراك حالي",
    noNext: "لا توجد فاتورة قادمة",
    noCurrentHint: "لا يوجد اشتراك حالي — هيظهر هنا أول ما يتفعّل اشتراك.",
    noNextHint: "لا يوجد اشتراك للشهر القادم بعد.",
    paid: "مدفوعة",
    unpaid: "غير مدفوعة",
    viewStudent: "عرض الطالب",
    // plan + month create dialog
    month: "الشهر",
    monthHint: "هيتم إنشاء اشتراك للشهر ده بساعات وسعر الخطة المختارة.",
    noPlans: "لا توجد خطط متاحة.",
    planHint: "{hours} ساعة · {price}",
    subscriptionExists: "يوجد اشتراك حسب الحصص لهذا الشهر بالفعل.",
    viewAll: "كل الاشتراكات",
  },
  en: {
    pageTitle: "Subscriptions",
    view: "View",
    renew: "Renew",
    renewTitle: "Renew subscription",
    renewSubmit: "Renew",
    confirmRenewActive: "There is still an active subscription, continue anyway?",
    discount: "Discount",
    basePrice: "Price before discount",
    netPrice: "Price after discount",
    coupon: "Coupon",
    pageDescriptionAdmin:
      "Review every subscription, approve pending requests, and create manual ones.",
    pageDescriptionParent: "Your children's subscriptions and their status.",
    pageDescriptionStudent: "Your subscriptions and their status.",
    create: "Manual subscription",
    student: "Student",
    allStudents: "All students",
    plan: "Plan",
    status: "Status",
    price: "Price",
    start: "Start",
    end: "End",
    hours: "Hours",
    actions: "Actions",
    approve: "Approve",
    reject: "Reject",
    cancelSubscription: "Cancel subscription",
    confirmCancel: "Cancel this subscription?",
    studentEmail: "Student email",
    parents: "Parents",
    allParents: "All parents",
    parentPhone: "Parent phone",
    parentEmail: "Parent email",
    PENDING: "Pending approval",
    UPCOMING: "Upcoming",
    ACTIVE: "Active",
    EXPIRED: "Expired",
    CANCELLED: "Cancelled",
    all: "All",
    createTitle: "Create a manual subscription",
    selectStudent: "Select student",
    selectPlan: "Select plan",
    billingPeriod: "Billing period",
    monthly: "Monthly",
    couponCode: "Coupon code (optional)",
    couponCodeHint: "If there's a coupon, enter its code to link it and apply the discount.",
    priceCouponNote: "The price will be computed after the discount on save.",
    priceCharged: "Price charged",
    subsHours: "Invoice duration",
    subsHoursHint: "The invoice is calculated from this duration.",
    remainingHours: "Remaining duration",
    editHours: "Edit duration",
    editHoursTitle: "Edit invoice duration",
    remainingHoursLabel: "Remaining minutes",
    remainingHoursHint: "Enter remaining minutes, such as 45, 60, or 90.",
    remainingExceedsSubs: "Remaining duration can't exceed subscription duration.",
    remainingMinutesInvalid: "Enter a whole number of minutes.",
    startDate: "Start date",
    endDate: "End date",
    save: "Save",
    cancel: "Cancel",
    required: "Required",
    rejectTitle: "Reject request",
    rejectReason: "Rejection reason (optional)",
    confirmApprove: "Approve this subscription?",
    empty: "No subscriptions yet.",
    // usage-based billing
    phase: {
      accumulating: "Accumulating",
      awaitingPayment: "Awaiting payment",
      upcoming: "Upcoming",
      active: "Active",
      ended: "Ended",
    },
    origin: "Type",
    originUsage: "Usage-based",
    originManual: "Manual",
    accumulatingTitle: "Next month's bill (building up)",
    liveHint: "Builds up from this month's sessions, billed next month",
    frozenHint: "Frozen — ready to invoice",
    usageManagedHint: "Auto-computed from sessions; closes at month end",
    currentTitle: "Current subscription",
    noCurrent: "No current subscription",
    noNext: "No upcoming bill",
    noCurrentHint: "No current subscription — it appears here once one is active.",
    noNextHint: "No subscription has been created for next month yet.",
    paid: "Paid",
    unpaid: "Unpaid",
    viewStudent: "View student",
    // plan + month create dialog
    month: "Month",
    monthHint: "A subscription for this month is created with the selected plan's hours and price.",
    noPlans: "No plans available.",
    planHint: "{hours} h · {price}",
    subscriptionExists: "A usage subscription for this month already exists.",
    viewAll: "All subscriptions",
  },
};

export function useSubscriptionsText() {
  const { lng } = useTranslation();
  return subscriptionsText[lng === "en" ? "en" : "ar"];
}
