"use client";

import { useTranslation } from "../../../i18n/client.js";

export const userDetailText = {
  ar: {
    // header
    back: "رجوع",
    roleAdmin: "معلّم",
    roleParent: "ولي أمر",
    roleStudent: "طالب",
    bannedChip: "محظور",
    activeChip: "نشط",
    inactiveChip: "غير نشط",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    noEmail: "لا يوجد بريد",
    noPhone: "لا يوجد هاتف",
    // tabs
    tabOverview: "نظرة عامة",
    tabBadges: "الأوسمة",
    tabCertificates: "الشهادات",
    tabEvaluations: "التقييمات",
    tabSubscriptions: "الاشتراكات",
    tabChildren: "الأبناء",
    // overview / student
    photoTitle: "صورة الطالب",
    photoHint: "صورة شخصية (PNG/JPEG/WEBP/GIF، بحد أقصى ٥ ميجابايت).",
    choosePhoto: "اختر صورة",
    uploadingPhoto: "جارٍ الرفع…",
    photoInvalidType: "يُرجى اختيار صورة بصيغة PNG أو JPEG أو WEBP أو GIF.",
    photoTooLarge: "يجب ألا يتجاوز حجم الصورة ٥ ميجابايت.",
    levelTitle: "المستوى التعليمي",
    levelLabel: "المستوى",
    saveLevel: "حفظ المستوى",
    pointsTotal: "إجمالي النقاط",
    points: "نقطة",
    parentsTitle: "أولياء الأمور",
    noParents: "لا يوجد أولياء أمور مرتبطون",
    relation: "صلة القرابة",
    FATHER: "الأب",
    MOTHER: "الأم",
    GUARDIAN: "وصي",
    OTHER: "أخرى",
    viewProfile: "عرض الملف",
    // overview / parent + admin
    contactTitle: "معلومات الاتصال",
    profileTitle: "الملف الشخصي",
    joinedOn: "تاريخ الانضمام",
    // badges
    awardBadge: "منح وسام",
    revoke: "سحب",
    revokeConfirm: "هل تريد سحب هذا الوسام من الطالب؟",
    noBadges: "لم يحصل الطالب على أي أوسمة بعد",
    awardedAt: "مُنح في",
    grantPoints: "منح نقاط",
    selectBadge: "اختر وساماً",
    award: "منح",
    awardSuccessHint: "اختر وساماً لمنحه لهذا الطالب.",
    pointsAmount: "عدد النقاط",
    pointsReason: "السبب (اختياري)",
    grant: "منح",
    // certificates
    certificatesTitle: "الشهادات",
    certificatesCount: "عدد الشهادات",
    viewCertificates: "عرض الشهادات",
    noCertificates: "لا توجد شهادات بعد",
    // evaluations
    gamesTitle: "محاولات الألعاب",
    quizzesTitle: "محاولات الاختبارات",
    score: "الدرجة",
    date: "التاريخ",
    result: "النتيجة",
    passed: "ناجح",
    failed: "راسب",
    noGameAttempts: "لا توجد محاولات ألعاب",
    noQuizAttempts: "لا توجد محاولات اختبارات",
    game: "اللعبة",
    quiz: "الاختبار",
    // subscriptions
    subscriptionsTitle: "الاشتراكات",
    addSubscription: "إضافة اشتراك",
    cancel: "إلغاء",
    cancelSub: "إلغاء الاشتراك",
    cancelConfirm: "هل تريد إلغاء هذا الاشتراك؟",
    plan: "الباقة",
    startDate: "تاريخ البدء",
    endDate: "تاريخ الانتهاء",
    status: "الحالة",
    noSubscriptions: "لا توجد اشتراكات",
    PENDING: "قيد الانتظار",
    UPCOMING: "قادم",
    ACTIVE: "نشط",
    EXPIRED: "منتهٍ",
    CANCELLED: "ملغى",
    // children
    childrenTitle: "الأبناء",
    childName: "الاسم",
    childLevel: "المستوى",
    childPoints: "النقاط",
    childSubscription: "الاشتراك",
    subscribed: "مشترك",
    notSubscribed: "غير مشترك",
    childCertificates: "الشهادات",
    details: "التفاصيل",
    noChildren: "لا يوجد أبناء مرتبطون",
    // header actions
    actions: "إجراءات",
    sendReport: "إرسال تقرير",
    sendInvite: "إرسال دعوة اختبار",
    ban: "حظر",
    unban: "إلغاء الحظر",
    banConfirm: "هل تريد حظر هذا الحساب؟ سيتم منع تسجيل الدخول.",
    unbanConfirm: "هل تريد إلغاء حظر هذا الحساب؟",
    banReasonLabel: "سبب الحظر (اختياري)",
    confirm: "تأكيد",
    // report dialog (reused inline)
    reportTitle: "إرسال تقرير",
    reportTitleLabel: "العنوان",
    reportBodyLabel: "المحتوى",
    reportDateLabel: "تاريخ التقرير",
    send: "إرسال",
    required: "هذا الحقل مطلوب",
    // generic
    notFound: "المستخدم غير موجود",
    notFoundBody: "تعذّر العثور على هذا المستخدم.",
    save: "حفظ",
    close: "إغلاق",
  },
  en: {
    back: "Back",
    roleAdmin: "Teacher",
    roleParent: "Parent",
    roleStudent: "Student",
    bannedChip: "Banned",
    activeChip: "Active",
    inactiveChip: "Inactive",
    email: "Email",
    phone: "Phone",
    noEmail: "No email",
    noPhone: "No phone",
    tabOverview: "Overview",
    tabBadges: "Badges",
    tabCertificates: "Certificates",
    tabEvaluations: "Evaluations",
    tabSubscriptions: "Subscriptions",
    tabChildren: "Children",
    photoTitle: "Student photo",
    photoHint: "A profile photo (PNG/JPEG/WEBP/GIF, up to 5MB).",
    choosePhoto: "Choose photo",
    uploadingPhoto: "Uploading…",
    photoInvalidType: "Please pick a PNG, JPEG, WEBP or GIF image.",
    photoTooLarge: "Image must be 5MB or smaller.",
    levelTitle: "Student level",
    levelLabel: "Level",
    saveLevel: "Save level",
    pointsTotal: "Total points",
    points: "pts",
    parentsTitle: "Parents",
    noParents: "No parents linked",
    relation: "Relation",
    FATHER: "Father",
    MOTHER: "Mother",
    GUARDIAN: "Guardian",
    OTHER: "Other",
    viewProfile: "View profile",
    contactTitle: "Contact information",
    profileTitle: "Profile",
    joinedOn: "Joined on",
    awardBadge: "Award badge",
    revoke: "Revoke",
    revokeConfirm: "Revoke this badge from the student?",
    noBadges: "This student has no badges yet",
    awardedAt: "Awarded on",
    grantPoints: "Grant points",
    selectBadge: "Select a badge",
    award: "Award",
    awardSuccessHint: "Pick a badge to award to this student.",
    pointsAmount: "Points amount",
    pointsReason: "Reason (optional)",
    grant: "Grant",
    certificatesTitle: "Certificates",
    certificatesCount: "Certificates count",
    viewCertificates: "View certificates",
    noCertificates: "No certificates yet",
    gamesTitle: "Game attempts",
    quizzesTitle: "Quiz attempts",
    score: "Score",
    date: "Date",
    result: "Result",
    passed: "Passed",
    failed: "Failed",
    noGameAttempts: "No game attempts",
    noQuizAttempts: "No quiz attempts",
    game: "Game",
    quiz: "Quiz",
    subscriptionsTitle: "Subscriptions",
    addSubscription: "Add subscription",
    cancel: "Cancel",
    cancelSub: "Cancel subscription",
    cancelConfirm: "Cancel this subscription?",
    plan: "Plan",
    startDate: "Start date",
    endDate: "End date",
    status: "Status",
    noSubscriptions: "No subscriptions",
    PENDING: "Pending",
    UPCOMING: "Upcoming",
    ACTIVE: "Active",
    EXPIRED: "Expired",
    CANCELLED: "Cancelled",
    childrenTitle: "Children",
    childName: "Name",
    childLevel: "Level",
    childPoints: "Points",
    childSubscription: "Subscription",
    subscribed: "Subscribed",
    notSubscribed: "Not subscribed",
    childCertificates: "Certificates",
    details: "Details",
    noChildren: "No children linked",
    actions: "Actions",
    sendReport: "Send report",
    sendInvite: "Send quiz invite",
    ban: "Ban",
    unban: "Unban",
    banConfirm: "Ban this account? Login will be blocked.",
    unbanConfirm: "Unban this account?",
    banReasonLabel: "Ban reason (optional)",
    confirm: "Confirm",
    reportTitle: "Send report",
    reportTitleLabel: "Title",
    reportBodyLabel: "Body",
    reportDateLabel: "Report date",
    send: "Send",
    required: "This field is required",
    notFound: "User not found",
    notFoundBody: "This user could not be found.",
    save: "Save",
    close: "Close",
  },
};

export function useUserDetailText() {
  const { lng } = useTranslation();
  return userDetailText[lng === "en" ? "en" : "ar"];
}
