"use client";

import { useTranslation } from "../../../i18n/client.js";

export const userDetailText = {
  ar: {
    // header
    back: "رجوع",
    roleAdmin: "معلّم",
    roleParent: "ولي أمر",
    roleStudent: "طالب",
    bannedChip: "محظور",
    activeChip: "نشط",
    inactiveChip: "غير نشط",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    noEmail: "لا يوجد بريد",
    noPhone: "لا يوجد هاتف",
    // tabs
    tabOverview: "نظرة عامة",
    tabProfile: "بيانات الحساب",
    tabBadges: "الأوسمة",
    tabCertificates: "الشهادات",
    tabEvaluations: "التقييمات",
    tabSubscriptions: "الاشتراكات",
    tabChildren: "الأبناء",
    // overview / student
    photoTitle: "صورة الطالب",
    photoHint: "صورة شخصية (PNG/JPEG/WEBP/GIF، بحد أقصى ٥ ميجابايت).",
    choosePhoto: "اختر صورة",
    uploadingPhoto: "جارٍ الرفع…",
    photoInvalidType: "يُرجى اختيار صورة بصيغة PNG أو JPEG أو WEBP أو GIF.",
    photoTooLarge: "يجب ألا يتجاوز حجم الصورة ٥ ميجابايت.",
    levelTitle: "المستوى التعليمي",
    levelLabel: "المستوى",
    saveLevel: "حفظ المستوى",
    pointsTotal: "إجمالي النقاط",
    points: "نقطة",
    parentsTitle: "أولياء الأمور",
    noParents: "لا يوجد أولياء أمور مرتبطون",
    relation: "صلة القرابة",
    FATHER: "الأب",
    MOTHER: "الأم",
    GUARDIAN: "وصي",
    OTHER: "أخرى",
    viewProfile: "عرض الملف",
    // overview / parent + admin
    contactTitle: "معلومات الاتصال",
    profileTitle: "الملف الشخصي",
    joinedOn: "تاريخ الانضمام",
    accountDetailsTitle: "بيانات الحساب",
    childAccountHint:
      "يمكن لولي الأمر تعديل بيانات الطفل وصورته واسم المستخدم وكلمة المرور.",
    parentAccountHint:
      "حدّث بياناتك وصورتك واسم المستخدم وكلمة المرور.",
    nameLabel: "الاسم",
    usernameLabel: "اسم المستخدم",
    usernameEditHint:
      "يمكن تغييره بشرط ألا يكون مستخدمًا في حساب آخر.",
    usernameAlreadyExists:
      "اسم المستخدم مستخدم بالفعل، اختر اسم مستخدم آخر.",
    nicknameLabel: "اللقب",
    emailRecoveryHint:
      "البريد اختياري إذا كان للحساب اسم مستخدم، لكنه مطلوب لاسترداد كلمة المرور.",
    identityRequired: "يجب أن يحتوي الحساب على بريد إلكتروني أو اسم مستخدم على الأقل",
    invalidEmail: "أدخل بريدًا إلكترونيًا صحيحًا",
    invalidUsername:
      "اسم المستخدم من 3 إلى 30 حرفًا، ويقبل الحروف والأرقام والنقطة والشرطة فقط",
    newPassword: "كلمة مرور جديدة",
    passwordLeaveBlank:
      "اترك كلمة المرور فارغة إذا كنت لا تريد تغييرها.",
    confirmPassword: "تأكيد كلمة المرور",
    passwordShort: "كلمة المرور يجب ألا تقل عن 6 أحرف",
    passwordsDontMatch: "كلمتا المرور غير متطابقتين",
    saveAccount: "حفظ بيانات الحساب",
    myProfileTitle: "ملفي الشخصي",
    myProfileDescription:
      "عدّل بيانات حسابك وصورتك واسم المستخدم وكلمة المرور.",
    notificationPreferencesTitle: "إعدادات الإشعارات",
    notificationPreferencesDescription:
      "اختر أين تريد استقبال إشعارات حسابك. الإعدادان مفعّلان تلقائيًا.",
    inAppNotificationsLabel: "إشعارات داخل الموقع",
    inAppNotificationsHint: "تظهر في مركز الإشعارات داخل حسابك.",
    emailNotificationsLabel: "إشعارات البريد الإلكتروني",
    emailNotificationsHint:
      "تُرسل إلى بريدك المسجّل، وفشل الإرسال لن يؤثر على أي عملية.",
    emailNotificationsNoEmailHint:
      "أضف بريدًا إلكترونيًا لحسابك حتى تصلك إشعارات البريد.",
    saveNotificationPreferences: "حفظ إعدادات الإشعارات",
    // badges
    awardBadge: "منح وسام",
    revoke: "سحب",
    revokeConfirm: "هل تريد سحب هذا الوسام من الطالب؟",
    noBadges: "لم يحصل الطالب على أي أوسمة بعد",
    awardedAt: "مُنح في",
    grantPoints: "منح نقاط",
    selectBadge: "اختر وساماً",
    award: "منح",
    awardSuccessHint: "اختر وساماً لمنحه لهذا الطالب.",
    pointsAmount: "عدد النقاط",
    pointsReason: "السبب (اختياري)",
    grant: "منح",
    // certificates
    certificatesTitle: "الشهادات",
    certificatesCount: "عدد الشهادات",
    viewCertificates: "عرض الشهادات",
    openCertificates: "فتح في صفحة الشهادات",
    grantCertificate: "منح شهادة",
    noCertificates: "لا توجد شهادات بعد",
    // games (assigned)
    tabGames: "الألعاب",
    assignedGamesTitle: "الألعاب المسندة",
    assignGame: "إسناد لعبة",
    selectGame: "اختر لعبة",
    removeGame: "إزالة",
    removeGameConfirm: "إزالة هذه اللعبة من الطالب؟",
    noAssignedGamesAdmin: "لا توجد ألعاب مسندة لهذا الطالب بعد",
    noGameToAssign: "مفيش ألعاب تانية تقدر تسندها",
    dueAt: "آخر موعد",
    assignmentASSIGNED: "مسندة",
    assignmentIN_PROGRESS: "بيلعب فيها",
    assignmentCOMPLETED: "خلّصها",
    // evaluations
    gamesTitle: "محاولات الألعاب",
    quizzesTitle: "محاولات الاختبارات",
    score: "الدرجة",
    date: "التاريخ",
    result: "النتيجة",
    passed: "ناجح",
    failed: "راسب",
    noGameAttempts: "لا توجد محاولات ألعاب",
    noQuizAttempts: "لا توجد محاولات اختبارات",
    game: "اللعبة",
    quiz: "الاختبار",
    // subscriptions moved to the shared SubscriptionsPage; only the generic keys
    // still consumed by other tabs (e.g. GamesTab status column) remain.
    cancel: "إلغاء",
    status: "الحالة",
    // children
    childrenTitle: "الأبناء",
    childName: "الاسم",
    childLevel: "المستوى",
    childPoints: "النقاط",
    childSubscription: "الاشتراك",
    subscribed: "مشترك",
    notSubscribed: "غير مشترك",
    childCertificates: "الشهادات",
    details: "التفاصيل",
    noChildren: "لا يوجد أبناء مرتبطون",
    // header actions
    actions: "إجراءات",
    sendReport: "إرسال تقرير",
    sendInvite: "إرسال دعوة اختبار",
    inviteBadgeLabel: "اربط وسامًا بهذه الدعوة (اختياري)",
    inviteBadgeHint: "إذا نجح الطالب في الاختبار، سيحصل على هذا الوسام مع الشهادة.",
    inviteNoBadge: "بدون وسام",
    inviteNoBadges: "لا توجد أوسمة متاحة",
    ban: "حظر",
    unban: "إلغاء الحظر",
    banConfirm: "هل تريد حظر هذا الحساب؟ سيتم منع تسجيل الدخول.",
    unbanConfirm: "هل تريد إلغاء حظر هذا الحساب؟",
    banReasonLabel: "سبب الحظر (اختياري)",
    confirm: "تأكيد",
    // report dialog (reused inline)
    reportTitle: "إرسال تقرير",
    reportTitleLabel: "العنوان",
    reportBodyLabel: "المحتوى",
    reportDateLabel: "تاريخ التقرير",
    send: "إرسال",
    required: "هذا الحقل مطلوب",
    // generic
    notFound: "المستخدم غير موجود",
    notFoundBody: "تعذّر العثور على هذا المستخدم.",
    save: "حفظ",
    close: "إغلاق",
  },
  en: {
    back: "Back",
    roleAdmin: "Teacher",
    roleParent: "Parent",
    roleStudent: "Student",
    bannedChip: "Banned",
    activeChip: "Active",
    inactiveChip: "Inactive",
    email: "Email",
    phone: "Phone",
    noEmail: "No email",
    noPhone: "No phone",
    tabOverview: "Overview",
    tabProfile: "Account",
    tabBadges: "Badges",
    tabCertificates: "Certificates",
    tabEvaluations: "Evaluations",
    tabSubscriptions: "Subscriptions",
    tabChildren: "Children",
    photoTitle: "Student photo",
    photoHint: "A profile photo (PNG/JPEG/WEBP/GIF, up to 5MB).",
    choosePhoto: "Choose photo",
    uploadingPhoto: "Uploading…",
    photoInvalidType: "Please pick a PNG, JPEG, WEBP or GIF image.",
    photoTooLarge: "Image must be 5MB or smaller.",
    levelTitle: "Student level",
    levelLabel: "Level",
    saveLevel: "Save level",
    pointsTotal: "Total points",
    points: "pts",
    parentsTitle: "Parents",
    noParents: "No parents linked",
    relation: "Relation",
    FATHER: "Father",
    MOTHER: "Mother",
    GUARDIAN: "Guardian",
    OTHER: "Other",
    viewProfile: "View profile",
    contactTitle: "Contact information",
    profileTitle: "Profile",
    joinedOn: "Joined on",
    accountDetailsTitle: "Account details",
    childAccountHint:
      "A parent can update the child's details, photo, username, and password.",
    parentAccountHint:
      "Update your details, photo, username, and password.",
    nameLabel: "Name",
    usernameLabel: "Username",
    usernameEditHint:
      "You can change it as long as it is not used by another account.",
    usernameAlreadyExists:
      "This username is already in use. Choose another username.",
    nicknameLabel: "Nickname",
    emailRecoveryHint:
      "Email is optional when the account has a username, but it is required for password recovery.",
    identityRequired: "The account must keep an email or username",
    invalidEmail: "Enter a valid email address",
    invalidUsername:
      "Username must be 3–30 characters using letters, numbers, dots, underscores or hyphens",
    newPassword: "New password",
    passwordLeaveBlank:
      "Leave the password blank if you do not want to change it.",
    confirmPassword: "Confirm password",
    passwordShort: "Password must be at least 6 characters",
    passwordsDontMatch: "Passwords do not match",
    saveAccount: "Save account",
    myProfileTitle: "My profile",
    myProfileDescription:
      "Update your account details, photo, username, and password.",
    notificationPreferencesTitle: "Notification settings",
    notificationPreferencesDescription:
      "Choose where you receive account notifications. Both options are enabled by default.",
    inAppNotificationsLabel: "In-app notifications",
    inAppNotificationsHint:
      "Show notifications in your account notification center.",
    emailNotificationsLabel: "Email notifications",
    emailNotificationsHint:
      "Send notifications to your registered email. Delivery failures never interrupt an operation.",
    emailNotificationsNoEmailHint:
      "Add an email address to your account to receive email notifications.",
    saveNotificationPreferences: "Save notification settings",
    awardBadge: "Award badge",
    revoke: "Revoke",
    revokeConfirm: "Revoke this badge from the student?",
    noBadges: "This student has no badges yet",
    awardedAt: "Awarded on",
    grantPoints: "Grant points",
    selectBadge: "Select a badge",
    award: "Award",
    awardSuccessHint: "Pick a badge to award to this student.",
    pointsAmount: "Points amount",
    pointsReason: "Reason (optional)",
    grant: "Grant",
    certificatesTitle: "Certificates",
    certificatesCount: "Certificates count",
    viewCertificates: "View certificates",
    openCertificates: "Open in certificates page",
    grantCertificate: "Grant certificate",
    noCertificates: "No certificates yet",
    // games (assigned)
    tabGames: "Games",
    assignedGamesTitle: "Assigned games",
    assignGame: "Assign game",
    selectGame: "Select a game",
    removeGame: "Remove",
    removeGameConfirm: "Remove this game from the student?",
    noAssignedGamesAdmin: "No games assigned to this student yet",
    noGameToAssign: "No other games to assign",
    dueAt: "Due date",
    assignmentASSIGNED: "Assigned",
    assignmentIN_PROGRESS: "In progress",
    assignmentCOMPLETED: "Completed",
    gamesTitle: "Game attempts",
    quizzesTitle: "Quiz attempts",
    score: "Score",
    date: "Date",
    result: "Result",
    passed: "Passed",
    failed: "Failed",
    noGameAttempts: "No game attempts",
    noQuizAttempts: "No quiz attempts",
    game: "Game",
    quiz: "Quiz",
    cancel: "Cancel",
    status: "Status",
    childrenTitle: "Children",
    childName: "Name",
    childLevel: "Level",
    childPoints: "Points",
    childSubscription: "Subscription",
    subscribed: "Subscribed",
    notSubscribed: "Not subscribed",
    childCertificates: "Certificates",
    details: "Details",
    noChildren: "No children linked",
    actions: "Actions",
    sendReport: "Send report",
    sendInvite: "Send quiz invite",
    inviteBadgeLabel: "Link a badge to this invitation (optional)",
    inviteBadgeHint: "If the student passes, they earn this badge with their certificate.",
    inviteNoBadge: "No badge",
    inviteNoBadges: "No badges available",
    ban: "Ban",
    unban: "Unban",
    banConfirm: "Ban this account? Login will be blocked.",
    unbanConfirm: "Unban this account?",
    banReasonLabel: "Ban reason (optional)",
    confirm: "Confirm",
    reportTitle: "Send report",
    reportTitleLabel: "Title",
    reportBodyLabel: "Body",
    reportDateLabel: "Report date",
    send: "Send",
    required: "This field is required",
    notFound: "User not found",
    notFoundBody: "This user could not be found.",
    save: "Save",
    close: "Close",
  },
};

export function useUserDetailText() {
  const { lng } = useTranslation();
  return userDetailText[lng === "en" ? "en" : "ar"];
}
