"use client";

import { useTranslation } from "../../../i18n/client.js";

export const usersText = {
  ar: {
    pageTitle: "المستخدمون",
    pageDescription: "أنشئ وعدّل حسابات المعلّمين وأولياء الأمور والطلاب وصلاحياتها.",
    parentsTitle: "أولياء الأمور",
    parentsDescription: "كل حسابات أولياء الأمور وأبنائهم المرتبطين بهم.",
    studentsTitle: "الطلاب",
    studentsDescription: "كل حسابات الطلاب وحالة اشتراكاتهم وأولياء أمورهم.",
    viewDetails: "عرض التفاصيل",
    childDetails: "التفاصيل",
    create: "مستخدم جديد",
    edit: "تعديل",
    delete: "إلغاء التفعيل",
    linkParent: "ربط ولي أمر",
    // columns
    name: "الاسم",
    email: "البريد الإلكتروني",
    username: "اسم المستخدم",
    phone: "رقم الهاتف",
    role: "الدور",
    childrenCount: "عدد الأبناء",
    active: "الحالة",
    createdAt: "تاريخ الإنشاء",
    actions: "إجراءات",
    noPhone: "—",
    // role labels
    admin: "معلّم",
    parent: "ولي أمر",
    student: "طالب",
    // status labels
    activeYes: "مُفعّل",
    activeNo: "موقوف",
    // form
    nameLabel: "الاسم",
    emailLabel: "البريد الإلكتروني",
    usernameLabel: "اسم المستخدم",
    usernameEditHint:
      "يمكن تغييره بشرط ألا يكون مستخدمًا في حساب آخر.",
    usernameAlreadyExists:
      "اسم المستخدم مستخدم بالفعل، اختر اسم مستخدم آخر.",
    passwordLabel: "كلمة المرور",
    passwordEditLabel: "كلمة المرور الجديدة (اتركها فارغة لعدم التغيير)",
    passwordLeaveBlank: "اتركها فارغة إذا كنت لا تريد تغيير كلمة المرور.",
    roleLabel: "الدور",
    phoneLabel: "رقم الهاتف",
    nicknameLabel: "الاسم المستعار",
    localeLabel: "لغة الواجهة",
    arabic: "العربية",
    english: "الإنجليزية",
    isActive: "مُفعّل",
    photoLabel: "صورة الطالب",
    choosePhoto: "اختر صورة",
    uploadingPhoto: "جارٍ الرفع…",
    photoHint: "PNG أو JPEG أو WEBP، بحد أقصى 5 ميجابايت.",
    required: "هذا الحقل مطلوب",
    identityRequired: "أدخل البريد الإلكتروني أو اسم المستخدم",
    invalidEmail: "البريد الإلكتروني غير صالح",
    invalidUsername:
      "اسم المستخدم من 3 إلى 30 حرفًا، ويقبل الحروف والأرقام والنقطة والشرطة فقط",
    save: "حفظ",
    cancel: "إلغاء",
    createTitle: "إنشاء مستخدم جديد",
    editTitle: "تعديل المستخدم",
    deleteConfirm: "هل تريد إلغاء تفعيل هذا المستخدم؟",
    // link-parent dialog
    linkParentTitle: "ربط ولي أمر بالطالب",
    selectParent: "اختر ولي الأمر",
    relation: "صلة القرابة",
    father: "أب",
    mother: "أم",
    guardian: "وصيّ",
    other: "أخرى",
    link: "ربط",
    linkHint: "اختر ولي أمر موجود لربطه بهذا الطالب.",
    noParents: "لا يوجد أولياء أمور.",
    // parents column
    parents: "أولياء الأمور",
    noParentsLinked: "لا يوجد",
    // subscription column
    subscription: "الاشتراك",
    subscribed: "مشترك",
    notSubscribed: "غير مشترك",
    // certificates action
    certificates: "الشهادات",
    // children dialog
    viewChildren: "عرض الأبناء",
    childrenTitle: "أبناء ولي الأمر",
    children: "الأبناء",
    childName: "الاسم",
    nickname: "الاسم المستعار",
    noChildren: "لا يوجد أبناء مرتبطون بهذا الحساب.",
    close: "إغلاق",
    // filters
    searchLabel: "بحث بالاسم أو البريد أو اسم المستخدم",
    statusLabel: "الحالة",
    all: "الكل",
  },
  en: {
    pageTitle: "Users",
    pageDescription: "Create and edit teacher, parent and student accounts and their access.",
    parentsTitle: "Parents",
    parentsDescription: "All parent accounts and their linked children.",
    studentsTitle: "Students",
    studentsDescription: "All student accounts with their subscription status and parents.",
    viewDetails: "View details",
    childDetails: "Details",
    create: "New user",
    edit: "Edit",
    delete: "Deactivate",
    linkParent: "Link parent",
    name: "Name",
    email: "Email",
    username: "Username",
    phone: "Phone",
    role: "Role",
    childrenCount: "Children",
    active: "Status",
    createdAt: "Created",
    actions: "Actions",
    noPhone: "—",
    admin: "Teacher",
    parent: "Parent",
    student: "Student",
    activeYes: "Active",
    activeNo: "Inactive",
    nameLabel: "Name",
    emailLabel: "Email",
    usernameLabel: "Username",
    usernameEditHint:
      "You can change it as long as it is not used by another account.",
    usernameAlreadyExists:
      "This username is already in use. Choose another username.",
    passwordLabel: "Password",
    passwordEditLabel: "New password (leave blank to keep)",
    passwordLeaveBlank:
      "Leave it blank if you do not want to change the password.",
    roleLabel: "Role",
    phoneLabel: "Phone",
    nicknameLabel: "Nickname",
    localeLabel: "Interface language",
    arabic: "Arabic",
    english: "English",
    isActive: "Active",
    photoLabel: "Student photo",
    choosePhoto: "Choose image",
    uploadingPhoto: "Uploading…",
    photoHint: "PNG, JPEG or WEBP, up to 5MB.",
    required: "This field is required",
    identityRequired: "Enter an email address or username",
    invalidEmail: "Invalid email address",
    invalidUsername:
      "Username must be 3–30 characters using letters, numbers, dots, underscores or hyphens",
    save: "Save",
    cancel: "Cancel",
    createTitle: "Create a new user",
    editTitle: "Edit user",
    deleteConfirm: "Deactivate this user?",
    linkParentTitle: "Link a parent to the student",
    selectParent: "Select parent",
    relation: "Relation",
    father: "Father",
    mother: "Mother",
    guardian: "Guardian",
    other: "Other",
    link: "Link",
    linkHint: "Pick an existing parent to link to this student.",
    noParents: "No parents found.",
    parents: "Parents",
    noParentsLinked: "None",
    subscription: "Subscription",
    subscribed: "Subscribed",
    notSubscribed: "Not subscribed",
    certificates: "Certificates",
    viewChildren: "View children",
    childrenTitle: "Parent's children",
    children: "Children",
    childName: "Name",
    nickname: "Nickname",
    noChildren: "No children are linked to this account.",
    close: "Close",
    searchLabel: "Search by name, email or username",
    statusLabel: "Status",
    all: "All",
  },
};

export function useUsersText() {
  const { lng } = useTranslation();
  return usersText[lng === "en" ? "en" : "ar"];
}
