"use client";

import { useTranslation } from "../../../i18n/client.js";

export const sessionLogText = {
  ar: {
    pageTitle: "تسجيل الحصص",
    pageDescription: "سجّل حصص الطلاب وتابع الحضور والتقييم شهريًا.",
    create: "تسجيل حصة",
    edit: "تعديل",
    delete: "حذف",
    // table
    student: "الطالب",
    subjects: "المواد",
    hours: "الساعات",
    rating: "التقييم",
    attendance: "الحضور",
    date: "التاريخ",
    teacher: "المعلّم",
    actions: "إجراءات",
    dash: "—",
    moreItems: "+{count}",
    // filters
    monthLabel: "الشهر",
    studentFilterLabel: "الطالب",
    allStudents: "كل الأبناء",
    // subjects
    QURAN_MEMORIZATION: "تحفيظ القرآن",
    TAJWEED_COURSES: "دورات التجويد",
    ARABIC_READING: "العربية للقراءة",
    ARABIC_SPEAKING: "العربية للمحادثة",
    QURANIC_ARABIC: "العربية القرآنية",
    ISLAMIC_STUDIES: "الدراسات الإسلامية",
    // subject groups
    QURAN_PROGRAMS: "برامج القرآن",
    ARABIC_LANGUAGE: "اللغة العربية",
    ISLAMIC_EDUCATION: "التربية الإسلامية",
    // ratings
    EXCELLENT: "ممتاز",
    VERY_GOOD: "جيد جدًا",
    GOOD: "جيد",
    FAIR: "مقبول",
    WEAK: "ضعيف",
    // attendance
    PRESENT: "حضور",
    ABSENT: "غياب",
    // form
    studentLabel: "الطالب",
    subjectsLabel: "المواد",
    durationLabel: "المدة (ساعات)",
    ratingLabel: "التقييم",
    reportLabel: "ملاحظات الحصة",
    teacherLabel: "المعلّم (اختياري — الافتراضي المعلّم الحالي)",
    sessionDateLabel: "تاريخ الحصة",
    attendanceLabel: "الحضور",
    selectStudent: "اختر الطالب",
    selectSubjects: "اختر المواد",
    selectTeacher: "اختر المعلّم",
    loadingStudents: "جارٍ تحميل الطلاب…",
    loadingTeachers: "جارٍ تحميل المعلّمين…",
    noRating: "بدون تقييم",
    required: "هذا الحقل مطلوب",
    subjectsRequired: "اختر مادة واحدة على الأقل",
    durationInvalid: "أدخل عدد ساعات صحيح",
    save: "حفظ",
    cancel: "إلغاء",
    createTitle: "تسجيل حصة",
    editTitle: "تعديل الحصة",
    deleteConfirm: "هل تريد حذف هذه الحصة؟",
    // empty
    emptyTitle: "لا توجد حصص مسجّلة",
    emptyBody: "ستظهر هنا حصص هذا الشهر بمجرد تسجيلها.",
  },
  en: {
    pageTitle: "Session Log",
    pageDescription: "Log student sessions and track attendance and ratings by month.",
    create: "Log a session",
    edit: "Edit",
    delete: "Delete",
    student: "Student",
    subjects: "Subjects",
    hours: "Hours",
    rating: "Rating",
    attendance: "Attendance",
    date: "Date",
    teacher: "Teacher",
    actions: "Actions",
    dash: "—",
    moreItems: "+{count}",
    monthLabel: "Month",
    studentFilterLabel: "Student",
    allStudents: "All children",
    QURAN_MEMORIZATION: "Quran memorization",
    TAJWEED_COURSES: "Tajweed courses",
    ARABIC_READING: "Arabic for reading",
    ARABIC_SPEAKING: "Arabic for speaking",
    QURANIC_ARABIC: "Quranic Arabic",
    ISLAMIC_STUDIES: "Islamic studies",
    QURAN_PROGRAMS: "Quran programs",
    ARABIC_LANGUAGE: "Arabic language",
    ISLAMIC_EDUCATION: "Islamic education",
    EXCELLENT: "Excellent",
    VERY_GOOD: "Very good",
    GOOD: "Good",
    FAIR: "Fair",
    WEAK: "Weak",
    PRESENT: "Present",
    ABSENT: "Absent",
    studentLabel: "Student",
    subjectsLabel: "Subjects",
    durationLabel: "Duration (hours)",
    ratingLabel: "Rating",
    reportLabel: "Session notes",
    teacherLabel: "Teacher (optional — defaults to the teacher)",
    sessionDateLabel: "Session date",
    attendanceLabel: "Attendance",
    selectStudent: "Select a student",
    selectSubjects: "Select subjects",
    selectTeacher: "Select a teacher",
    loadingStudents: "Loading students…",
    loadingTeachers: "Loading teachers…",
    noRating: "No rating",
    required: "This field is required",
    subjectsRequired: "Select at least one subject",
    durationInvalid: "Enter a valid number of hours",
    save: "Save",
    cancel: "Cancel",
    createTitle: "Log a session",
    editTitle: "Edit session",
    deleteConfirm: "Delete this session?",
    emptyTitle: "No sessions logged",
    emptyBody: "This month's sessions will appear here once they're logged.",
  },
};

export function useSessionLogText() {
  const { lng } = useTranslation();
  return sessionLogText[lng === "en" ? "en" : "ar"];
}
